import type { DialogueLesson, DialogueLine } from "./dialogues";

type Pair = readonly [string, string];
type StageId = DialogueLesson["stageId"];

type Scenario = {
  id: string;
  title: Pair;
  topic: Pair;
  place: Pair;
  need: Pair;
  obstacle: Pair;
  optionA: Pair;
  optionB: Pair;
  result: Pair;
  value: Pair;
  sourceBasis: "Taskmaster" | "MultiWOZ" | "Schema-Guided Dialogue" | "DRAL";
};

const scenarios: Scenario[] = [
  { id: "breakfast", title: ["A Quick Breakfast", "Bữa sáng nhanh"], topic: ["daily routines", "thói quen hằng ngày"], place: ["at home", "ở nhà"], need: ["leave on time", "rời nhà đúng giờ"], obstacle: ["we have only fifteen minutes", "chúng ta chỉ còn mười lăm phút"], optionA: ["make toast and fruit", "chuẩn bị bánh mì nướng và trái cây"], optionB: ["buy something near school", "mua đồ ăn gần trường"], result: ["everyone starts the day calmly", "mọi người bắt đầu ngày mới bình tĩnh"], value: ["a simple plan saves time", "một kế hoạch đơn giản giúp tiết kiệm thời gian"], sourceBasis: "DRAL" },
  { id: "library", title: ["Finding the Right Book", "Tìm đúng cuốn sách"], topic: ["using a library", "sử dụng thư viện"], place: ["at the local library", "tại thư viện địa phương"], need: ["find a book for a class project", "tìm sách cho dự án trên lớp"], obstacle: ["the catalogue shows several similar titles", "danh mục có nhiều tựa sách giống nhau"], optionA: ["ask the librarian for the beginner section", "hỏi thủ thư về khu sách cơ bản"], optionB: ["read the summaries before borrowing", "đọc phần tóm tắt trước khi mượn"], result: ["the learner chooses a useful book", "người học chọn được cuốn sách hữu ích"], value: ["a clear question makes searching easier", "một câu hỏi rõ ràng giúp tìm kiếm dễ hơn"], sourceBasis: "Taskmaster" },
  { id: "restaurant", title: ["A Meal Everyone Can Enjoy", "Bữa ăn phù hợp với mọi người"], topic: ["ordering food", "gọi món"], place: ["at a neighbourhood restaurant", "tại một nhà hàng gần nhà"], need: ["choose a meal for two people", "chọn bữa ăn cho hai người"], obstacle: ["one person cannot eat peanuts", "một người không thể ăn đậu phộng"], optionA: ["ask about the ingredients", "hỏi về nguyên liệu"], optionB: ["choose the grilled vegetable dish", "chọn món rau nướng"], result: ["they order safely and enjoy the meal", "họ gọi món an toàn và thưởng thức bữa ăn"], value: ["specific information prevents mistakes", "thông tin cụ thể giúp tránh sai sót"], sourceBasis: "MultiWOZ" },
  { id: "bus", title: ["The Best Bus Route", "Tuyến xe buýt phù hợp nhất"], topic: ["public transport", "phương tiện công cộng"], place: ["at a bus stop", "tại trạm xe buýt"], need: ["reach the city centre before nine", "đến trung tâm thành phố trước chín giờ"], obstacle: ["the direct bus is delayed", "xe buýt đi thẳng đang bị hoãn"], optionA: ["take route twelve and change once", "đi tuyến mười hai và đổi xe một lần"], optionB: ["wait twenty minutes for the direct bus", "chờ hai mươi phút cho chuyến đi thẳng"], result: ["the passenger arrives on time", "hành khách đến đúng giờ"], value: ["checking alternatives reduces travel stress", "kiểm tra phương án khác giúp giảm căng thẳng khi đi lại"], sourceBasis: "MultiWOZ" },
  { id: "hotel", title: ["A Quiet Hotel Room", "Phòng khách sạn yên tĩnh"], topic: ["hotel check-in", "nhận phòng khách sạn"], place: ["at a hotel reception desk", "tại quầy lễ tân khách sạn"], need: ["get a quiet room for two nights", "nhận một phòng yên tĩnh trong hai đêm"], obstacle: ["the first room faces a busy road", "phòng đầu tiên hướng ra con đường đông đúc"], optionA: ["request a room at the back", "yêu cầu một phòng ở phía sau"], optionB: ["use earplugs and keep the original room", "dùng nút tai và giữ phòng ban đầu"], result: ["the guest can rest comfortably", "khách có thể nghỉ ngơi thoải mái"], value: ["a polite request can solve a practical problem", "một yêu cầu lịch sự có thể giải quyết vấn đề thực tế"], sourceBasis: "MultiWOZ" },
  { id: "train", title: ["Changing a Train Ticket", "Đổi vé tàu"], topic: ["train travel", "đi tàu"], place: ["at the railway station", "tại ga tàu"], need: ["travel one day later", "đi muộn hơn một ngày"], obstacle: ["the original ticket has a change fee", "vé ban đầu có phí đổi"], optionA: ["pay the fee for an evening train", "trả phí để đi chuyến tàu buổi tối"], optionB: ["buy a cheaper early ticket", "mua vé sớm rẻ hơn"], result: ["the traveller changes the plan within budget", "người đi đổi được kế hoạch trong ngân sách"], value: ["comparing the total cost leads to a better choice", "so sánh tổng chi phí dẫn đến lựa chọn tốt hơn"], sourceBasis: "MultiWOZ" },
  { id: "airport", title: ["A Gate Change", "Thay đổi cửa ra máy bay"], topic: ["air travel", "đi máy bay"], place: ["at an airport", "tại sân bay"], need: ["reach the correct gate", "đến đúng cửa ra máy bay"], obstacle: ["the gate changed after check-in", "cửa ra máy bay thay đổi sau khi làm thủ tục"], optionA: ["follow the updated signs", "đi theo biển chỉ dẫn mới"], optionB: ["ask an airport employee to confirm", "nhờ nhân viên sân bay xác nhận"], result: ["the passenger boards without rushing", "hành khách lên máy bay mà không phải vội"], value: ["confirming new information avoids confusion", "xác nhận thông tin mới giúp tránh nhầm lẫn"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "appointment", title: ["Moving an Appointment", "Dời lịch hẹn"], topic: ["making appointments", "đặt lịch hẹn"], place: ["during a phone call", "trong một cuộc gọi"], need: ["move an appointment to Thursday", "dời lịch hẹn sang thứ Năm"], obstacle: ["the usual morning time is full", "khung giờ sáng thường lệ đã kín"], optionA: ["accept a late-afternoon time", "nhận khung giờ cuối buổi chiều"], optionB: ["choose Friday morning instead", "chọn sáng thứ Sáu thay thế"], result: ["both sides confirm a workable time", "hai bên xác nhận được thời gian phù hợp"], value: ["repeating the date prevents scheduling errors", "nhắc lại ngày giúp tránh lỗi lịch hẹn"], sourceBasis: "Taskmaster" },
  { id: "shopping", title: ["Choosing a Useful Gift", "Chọn một món quà hữu ích"], topic: ["shopping for a gift", "mua quà"], place: ["at a small shop", "tại một cửa hàng nhỏ"], need: ["find a present for a friend", "tìm quà cho một người bạn"], obstacle: ["the friend already owns many decorations", "người bạn đã có nhiều đồ trang trí"], optionA: ["buy a reusable travel cup", "mua một cốc du lịch tái sử dụng"], optionB: ["choose a bookshop voucher", "chọn phiếu quà tặng hiệu sách"], result: ["the gift matches the friend’s interests", "món quà phù hợp sở thích của người bạn"], value: ["thinking about the receiver matters more than price", "nghĩ về người nhận quan trọng hơn giá tiền"], sourceBasis: "Taskmaster" },
  { id: "clothes", title: ["The Right Jacket", "Chiếc áo khoác phù hợp"], topic: ["buying clothes", "mua quần áo"], place: ["at a clothing store", "tại cửa hàng quần áo"], need: ["choose a jacket for rainy weather", "chọn áo khoác cho thời tiết mưa"], obstacle: ["the stylish jacket is not waterproof", "chiếc áo thời trang không chống nước"], optionA: ["choose the practical waterproof jacket", "chọn áo chống nước thiết thực"], optionB: ["keep looking for another style", "tiếp tục tìm kiểu khác"], result: ["the customer buys something suitable", "khách hàng mua được món đồ phù hợp"], value: ["purpose should guide a purchase", "mục đích nên định hướng việc mua sắm"], sourceBasis: "Taskmaster" },
  { id: "movie", title: ["Picking a Movie", "Chọn một bộ phim"], topic: ["movies and entertainment", "phim ảnh và giải trí"], place: ["while planning an evening out", "khi lên kế hoạch đi chơi buổi tối"], need: ["choose a film everyone will enjoy", "chọn phim mọi người đều thích"], obstacle: ["one friend dislikes scary films", "một người bạn không thích phim kinh dị"], optionA: ["watch a light comedy", "xem một bộ phim hài nhẹ nhàng"], optionB: ["choose an adventure film", "chọn một bộ phim phiêu lưu"], result: ["the group agrees without leaving anyone out", "cả nhóm đồng ý mà không bỏ quên ai"], value: ["a shared plan should consider everyone", "kế hoạch chung nên cân nhắc mọi người"], sourceBasis: "Taskmaster" },
  { id: "music", title: ["Tickets for a Concert", "Vé xem hòa nhạc"], topic: ["events and tickets", "sự kiện và vé"], place: ["on an event-booking website", "trên trang đặt vé sự kiện"], need: ["book three seats together", "đặt ba chỗ ngồi cạnh nhau"], obstacle: ["the cheapest section has only separate seats", "khu rẻ nhất chỉ còn ghế tách rời"], optionA: ["pay slightly more for adjacent seats", "trả thêm một chút cho ghế cạnh nhau"], optionB: ["attend the later performance", "tham dự suất diễn muộn hơn"], result: ["the friends make a plan they all accept", "những người bạn có kế hoạch mà tất cả chấp nhận"], value: ["the experience can matter more than the smallest saving", "trải nghiệm có thể quan trọng hơn khoản tiết kiệm nhỏ nhất"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "weather", title: ["Plans for a Rainy Day", "Kế hoạch cho ngày mưa"], topic: ["weather and plans", "thời tiết và kế hoạch"], place: ["during a weekend conversation", "trong cuộc trò chuyện cuối tuần"], need: ["keep a family outing", "duy trì chuyến đi chơi gia đình"], obstacle: ["heavy rain is expected all afternoon", "dự báo mưa lớn suốt buổi chiều"], optionA: ["visit the science museum", "tham quan bảo tàng khoa học"], optionB: ["move the picnic to Sunday", "dời buổi dã ngoại sang Chủ nhật"], result: ["the family still spends time together", "gia đình vẫn dành thời gian bên nhau"], value: ["flexibility keeps a plan enjoyable", "sự linh hoạt giúp kế hoạch vẫn thú vị"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "school-project", title: ["Dividing the Project Fairly", "Chia dự án công bằng"], topic: ["school teamwork", "làm việc nhóm ở trường"], place: ["in a classroom", "trong lớp học"], need: ["finish a presentation by Friday", "hoàn thành bài thuyết trình trước thứ Sáu"], obstacle: ["two students chose the same task", "hai học sinh chọn cùng một nhiệm vụ"], optionA: ["divide research by subtopic", "chia phần nghiên cứu theo chủ đề nhỏ"], optionB: ["let one student design the slides", "để một học sinh thiết kế slide"], result: ["everyone has a clear and fair role", "mọi người có vai trò rõ ràng và công bằng"], value: ["clear ownership improves teamwork", "trách nhiệm rõ ràng giúp làm việc nhóm tốt hơn"], sourceBasis: "DRAL" },
  { id: "work-meeting", title: ["A More Focused Meeting", "Cuộc họp tập trung hơn"], topic: ["workplace communication", "giao tiếp nơi làm việc"], place: ["at the office", "tại văn phòng"], need: ["make a decision in thirty minutes", "đưa ra quyết định trong ba mươi phút"], obstacle: ["the discussion keeps moving off topic", "cuộc thảo luận liên tục đi lệch chủ đề"], optionA: ["return to the three agenda questions", "quay lại ba câu hỏi trong chương trình"], optionB: ["schedule a separate discussion for new ideas", "xếp một cuộc trao đổi riêng cho ý tưởng mới"], result: ["the team decides and records the next steps", "nhóm đưa ra quyết định và ghi lại bước tiếp theo"], value: ["structure protects time without silencing ideas", "cấu trúc bảo vệ thời gian mà không dập tắt ý tưởng"], sourceBasis: "DRAL" },
  { id: "remote-work", title: ["A Productive Remote Day", "Một ngày làm từ xa hiệu quả"], topic: ["remote work", "làm việc từ xa"], place: ["during a team check-in", "trong buổi cập nhật nhóm"], need: ["complete a report without interruptions", "hoàn thành báo cáo mà không bị gián đoạn"], obstacle: ["several meetings split the morning", "nhiều cuộc họp chia nhỏ buổi sáng"], optionA: ["combine updates into one meeting", "gộp cập nhật vào một cuộc họp"], optionB: ["protect a two-hour focus block", "dành riêng hai giờ tập trung"], result: ["the report is finished and the team stays informed", "báo cáo hoàn thành và nhóm vẫn nắm thông tin"], value: ["availability and concentration need balance", "khả năng sẵn sàng và sự tập trung cần được cân bằng"], sourceBasis: "DRAL" },
  { id: "phone", title: ["A Phone That Will Not Charge", "Điện thoại không sạc được"], topic: ["technical support", "hỗ trợ kỹ thuật"], place: ["at an electronics service desk", "tại quầy dịch vụ điện tử"], need: ["make the phone charge normally", "làm điện thoại sạc bình thường"], obstacle: ["a different cable does not solve the problem", "dùng dây khác vẫn không giải quyết được"], optionA: ["clean and test the charging port", "làm sạch và kiểm tra cổng sạc"], optionB: ["leave the phone for a full inspection", "để lại điện thoại để kiểm tra toàn diện"], result: ["the cause is identified before money is spent", "nguyên nhân được xác định trước khi tốn tiền"], value: ["testing simple causes first avoids waste", "kiểm tra nguyên nhân đơn giản trước giúp tránh lãng phí"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "bank", title: ["A Card Payment Problem", "Sự cố thanh toán bằng thẻ"], topic: ["banking services", "dịch vụ ngân hàng"], place: ["during a support chat", "trong cuộc trò chuyện hỗ trợ"], need: ["understand a declined payment", "hiểu lý do thanh toán bị từ chối"], obstacle: ["the account has enough money", "tài khoản có đủ tiền"], optionA: ["confirm the recent transaction", "xác nhận giao dịch gần đây"], optionB: ["use a temporary digital card", "dùng thẻ kỹ thuật số tạm thời"], result: ["the account remains secure and payment resumes", "tài khoản vẫn an toàn và thanh toán tiếp tục"], value: ["security checks should be clear as well as careful", "kiểm tra bảo mật nên vừa rõ ràng vừa cẩn trọng"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "lost-item", title: ["A Bag Left Behind", "Chiếc túi bị bỏ quên"], topic: ["lost and found", "đồ thất lạc"], place: ["at a community centre", "tại trung tâm cộng đồng"], need: ["find a missing sports bag", "tìm một túi thể thao bị mất"], obstacle: ["several similar bags were used that day", "hôm đó có nhiều túi giống nhau"], optionA: ["describe the label and contents", "mô tả nhãn và đồ bên trong"], optionB: ["check the room where the class ended", "kiểm tra căn phòng nơi lớp học kết thúc"], result: ["the correct bag is returned to its owner", "chiếc túi đúng được trả cho chủ"], value: ["distinct details make identification reliable", "chi tiết khác biệt giúp nhận dạng đáng tin cậy"], sourceBasis: "MultiWOZ" },
  { id: "neighbour", title: ["Sharing a Quiet Building", "Cùng giữ tòa nhà yên tĩnh"], topic: ["neighbour relationships", "quan hệ hàng xóm"], place: ["in an apartment building", "trong một tòa nhà chung cư"], need: ["reduce noise after ten", "giảm tiếng ồn sau mười giờ"], obstacle: ["a neighbour works late and cooks at night", "một người hàng xóm làm muộn và nấu ăn ban đêm"], optionA: ["move noisy equipment away from the wall", "dời thiết bị ồn khỏi bức tường"], optionB: ["prepare meals earlier when possible", "chuẩn bị bữa ăn sớm hơn khi có thể"], result: ["both neighbours keep their routines with less conflict", "hai người vẫn giữ thói quen với ít xung đột hơn"], value: ["understanding context makes compromise possible", "hiểu hoàn cảnh giúp thỏa hiệp khả thi"], sourceBasis: "DRAL" },
  { id: "health-routine", title: ["Building a Sleep Routine", "Xây dựng thói quen ngủ"], topic: ["healthy routines", "thói quen lành mạnh"], place: ["during a conversation with a friend", "trong cuộc trò chuyện với bạn"], need: ["sleep more regularly", "ngủ đều đặn hơn"], obstacle: ["late messages keep waking the phone", "tin nhắn muộn liên tục làm điện thoại sáng"], optionA: ["schedule a do-not-disturb period", "đặt khoảng thời gian không làm phiền"], optionB: ["charge the phone outside the bedroom", "sạc điện thoại ngoài phòng ngủ"], result: ["the person rests better without becoming unreachable", "người đó nghỉ tốt hơn mà không mất liên lạc"], value: ["small environmental changes support good habits", "thay đổi nhỏ trong môi trường hỗ trợ thói quen tốt"], sourceBasis: "DRAL" },
  { id: "sports", title: ["Joining a Sports Class", "Tham gia lớp thể thao"], topic: ["sports and fitness", "thể thao và vận động"], place: ["at a recreation centre", "tại trung tâm thể thao"], need: ["choose a suitable weekly class", "chọn một lớp hằng tuần phù hợp"], obstacle: ["the beginner class conflicts with work", "lớp cơ bản trùng giờ làm"], optionA: ["try the mixed-level Saturday class", "thử lớp nhiều trình độ vào thứ Bảy"], optionB: ["join the waiting list for an evening class", "tham gia danh sách chờ cho lớp buổi tối"], result: ["the learner starts safely at a workable time", "người học bắt đầu an toàn vào thời gian phù hợp"], value: ["a sustainable schedule supports progress", "lịch trình bền vững hỗ trợ tiến bộ"], sourceBasis: "Taskmaster" },
  { id: "community", title: ["Planning a Clean-Up Day", "Lập kế hoạch ngày dọn dẹp"], topic: ["community volunteering", "tình nguyện cộng đồng"], place: ["at a neighbourhood meeting", "tại cuộc họp khu phố"], need: ["organise a park clean-up", "tổ chức dọn dẹp công viên"], obstacle: ["only a small number of volunteers have registered", "chỉ có ít tình nguyện viên đăng ký"], optionA: ["focus on the playground area first", "tập trung vào khu sân chơi trước"], optionB: ["invite local groups to take one section each", "mời các nhóm địa phương phụ trách từng khu"], result: ["the work is realistic and visible", "công việc thực tế và có kết quả rõ"], value: ["a smaller completed goal builds trust", "mục tiêu nhỏ được hoàn thành giúp xây dựng niềm tin"], sourceBasis: "DRAL" },
  { id: "energy", title: ["Saving Energy at School", "Tiết kiệm năng lượng ở trường"], topic: ["environmental action", "hành động vì môi trường"], place: ["during a student council meeting", "trong cuộc họp hội học sinh"], need: ["reduce unnecessary electricity use", "giảm sử dụng điện không cần thiết"], obstacle: ["people forget to switch off empty rooms", "mọi người quên tắt điện ở phòng trống"], optionA: ["place clear reminders by the doors", "đặt lời nhắc rõ ràng cạnh cửa"], optionB: ["assign a final room check each day", "phân công kiểm tra phòng cuối ngày"], result: ["energy use falls without disrupting lessons", "mức dùng năng lượng giảm mà không ảnh hưởng giờ học"], value: ["a good system makes responsible action easier", "một hệ thống tốt giúp hành động có trách nhiệm dễ hơn"], sourceBasis: "DRAL" },
  { id: "presentation", title: ["Making the Main Point Clear", "Làm rõ ý chính"], topic: ["presentations", "thuyết trình"], place: ["during a practice session", "trong buổi luyện tập"], need: ["explain a proposal in five minutes", "giải thích đề xuất trong năm phút"], obstacle: ["the draft contains too many background details", "bản nháp có quá nhiều chi tiết nền"], optionA: ["state the recommendation first", "nêu khuyến nghị trước"], optionB: ["move supporting data to questions", "chuyển dữ liệu hỗ trợ sang phần câu hỏi"], result: ["the audience understands the decision and reasons", "khán giả hiểu quyết định và lý do"], value: ["clarity comes from choosing what matters most", "sự rõ ràng đến từ việc chọn điều quan trọng nhất"], sourceBasis: "DRAL" },
  { id: "feedback", title: ["Feedback That Helps", "Phản hồi hữu ích"], topic: ["giving feedback", "đưa phản hồi"], place: ["after a team task", "sau một nhiệm vụ nhóm"], need: ["help a colleague improve", "giúp đồng nghiệp cải thiện"], obstacle: ["the first comment sounds too general", "nhận xét đầu tiên nghe quá chung chung"], optionA: ["name one effective behaviour", "nêu một hành vi hiệu quả"], optionB: ["suggest one observable next step", "đề xuất một bước tiếp theo có thể quan sát"], result: ["the colleague knows what to keep and change", "đồng nghiệp biết điều gì nên giữ và thay đổi"], value: ["specific feedback respects effort and supports growth", "phản hồi cụ thể tôn trọng nỗ lực và hỗ trợ phát triển"], sourceBasis: "DRAL" },
  { id: "career", title: ["Choosing the Next Career Step", "Chọn bước nghề nghiệp tiếp theo"], topic: ["career decisions", "quyết định nghề nghiệp"], place: ["during a mentoring conversation", "trong cuộc trò chuyện cố vấn"], need: ["choose between two job offers", "chọn giữa hai lời mời làm việc"], obstacle: ["the higher salary comes with less learning", "mức lương cao hơn đi kèm ít cơ hội học hỏi hơn"], optionA: ["choose short-term financial stability", "chọn sự ổn định tài chính ngắn hạn"], optionB: ["prioritise growth and mentorship", "ưu tiên phát triển và cố vấn"], result: ["the decision reflects present needs and future goals", "quyết định phản ánh nhu cầu hiện tại và mục tiêu tương lai"], value: ["a strong choice is aligned, not universally perfect", "lựa chọn tốt là lựa chọn phù hợp chứ không hoàn hảo cho mọi người"], sourceBasis: "DRAL" },
  { id: "policy", title: ["A Fair Use Policy", "Chính sách sử dụng công bằng"], topic: ["rules and fairness", "quy tắc và sự công bằng"], place: ["during a public discussion", "trong một cuộc thảo luận công khai"], need: ["set a fair rule for a shared space", "đặt quy tắc công bằng cho không gian chung"], obstacle: ["equal time does not meet every group’s needs", "thời gian bằng nhau không đáp ứng nhu cầu của mọi nhóm"], optionA: ["keep one simple rule for everyone", "giữ một quy tắc đơn giản cho mọi người"], optionB: ["allow transparent exceptions with clear criteria", "cho phép ngoại lệ minh bạch với tiêu chí rõ"], result: ["the policy is consistent without becoming rigid", "chính sách nhất quán mà không cứng nhắc"], value: ["fairness requires both principles and attention to context", "công bằng cần cả nguyên tắc lẫn sự chú ý đến hoàn cảnh"], sourceBasis: "DRAL" },
  { id: "parenting", title: ["A Calm Morning with Children", "Buổi sáng bình tĩnh cùng con"], topic: ["parenting and family", "gia đình và nuôi dạy con"], place: ["at home before school", "ở nhà trước giờ đi học"], need: ["help the children get ready independently", "giúp trẻ tự chuẩn bị đi học"], obstacle: ["everyone looks for things at the last minute", "mọi người tìm đồ vào phút cuối"], optionA: ["prepare a picture checklist", "chuẩn bị danh sách bằng hình ảnh"], optionB: ["pack school bags the night before", "soạn cặp từ tối hôm trước"], result: ["the family leaves without arguing", "gia đình rời nhà mà không tranh cãi"], value: ["routines can support independence without becoming harsh", "thói quen có thể hỗ trợ tính tự lập mà không cứng nhắc"], sourceBasis: "DRAL" },
  { id: "pet-care", title: ["Caring for a New Pet", "Chăm sóc thú cưng mới"], topic: ["pets and responsibility", "thú cưng và trách nhiệm"], place: ["during a family conversation", "trong cuộc trò chuyện gia đình"], need: ["share the daily care of a new dog", "chia sẻ việc chăm sóc chú chó mới hằng ngày"], obstacle: ["the morning schedule is already busy", "lịch buổi sáng đã bận rộn"], optionA: ["take turns with the morning walk", "luân phiên dắt chó đi buổi sáng"], optionB: ["move the longer walk to the evening", "chuyển buổi đi dài sang buổi tối"], result: ["the pet receives consistent care", "thú cưng được chăm sóc đều đặn"], value: ["enthusiasm must be matched by reliable responsibility", "sự hào hứng phải đi cùng trách nhiệm đáng tin cậy"], sourceBasis: "DRAL" },
  { id: "cooking", title: ["Cooking with What We Have", "Nấu ăn với nguyên liệu sẵn có"], topic: ["cooking at home", "nấu ăn tại nhà"], place: ["in the kitchen", "trong bếp"], need: ["prepare dinner without another shopping trip", "chuẩn bị bữa tối mà không phải đi mua thêm"], obstacle: ["one ingredient in the recipe is missing", "thiếu một nguyên liệu trong công thức"], optionA: ["replace it with seasonal vegetables", "thay bằng rau theo mùa"], optionB: ["choose a simpler recipe", "chọn một công thức đơn giản hơn"], result: ["the meal is tasty and food is not wasted", "bữa ăn ngon và thực phẩm không bị lãng phí"], value: ["flexibility is an important part of practical cooking", "linh hoạt là phần quan trọng của nấu ăn thực tế"], sourceBasis: "Taskmaster" },
  { id: "housing", title: ["A Repair in the Apartment", "Sửa chữa trong căn hộ"], topic: ["housing and repairs", "nhà ở và sửa chữa"], place: ["during a call with the building manager", "trong cuộc gọi với quản lý tòa nhà"], need: ["repair a leaking kitchen tap", "sửa vòi bếp bị rò"], obstacle: ["the first available visit is during work hours", "lịch sửa sớm nhất rơi vào giờ làm"], optionA: ["authorise the manager to enter", "ủy quyền cho quản lý vào nhà"], optionB: ["request the first Saturday appointment", "yêu cầu lịch đầu tiên vào thứ Bảy"], result: ["the leak is fixed without creating a security concern", "chỗ rò được sửa mà không tạo lo ngại an ninh"], value: ["access arrangements should be convenient and explicit", "thỏa thuận ra vào nên thuận tiện và rõ ràng"], sourceBasis: "MultiWOZ" },
  { id: "personal-finance", title: ["Planning a Monthly Budget", "Lập ngân sách hằng tháng"], topic: ["personal finance", "tài chính cá nhân"], place: ["during a household planning session", "trong buổi lập kế hoạch gia đình"], need: ["save regularly for an emergency fund", "tiết kiệm đều đặn cho quỹ khẩn cấp"], obstacle: ["small unplanned purchases add up", "các khoản mua nhỏ ngoài kế hoạch cộng lại khá lớn"], optionA: ["set an automatic transfer on payday", "đặt chuyển khoản tự động vào ngày nhận lương"], optionB: ["review flexible spending each week", "xem lại chi tiêu linh hoạt mỗi tuần"], result: ["saving becomes steady without ignoring daily needs", "việc tiết kiệm đều đặn mà không bỏ qua nhu cầu hằng ngày"], value: ["a useful budget guides choices rather than punishing people", "ngân sách hữu ích định hướng lựa chọn chứ không trừng phạt con người"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "public-service", title: ["Renewing an Important Document", "Gia hạn giấy tờ quan trọng"], topic: ["public services", "dịch vụ công"], place: ["at a local service centre", "tại trung tâm dịch vụ địa phương"], need: ["renew an identification document", "gia hạn giấy tờ tùy thân"], obstacle: ["one supporting document is out of date", "một giấy tờ hỗ trợ đã hết hạn"], optionA: ["upload a newer digital copy", "tải lên bản điện tử mới hơn"], optionB: ["return with the original tomorrow", "quay lại với bản gốc vào ngày mai"], result: ["the application is completed correctly", "hồ sơ được hoàn tất đúng cách"], value: ["clear requirements make public services more accessible", "yêu cầu rõ ràng giúp dịch vụ công dễ tiếp cận hơn"], sourceBasis: "Schema-Guided Dialogue" },
  { id: "emergency", title: ["Responding to a Minor Emergency", "Ứng phó tình huống khẩn cấp nhỏ"], topic: ["safety and emergencies", "an toàn và tình huống khẩn cấp"], place: ["at a community event", "tại một sự kiện cộng đồng"], need: ["help someone who has slipped", "giúp một người vừa bị trượt ngã"], obstacle: ["the person feels dizzy when standing", "người đó cảm thấy chóng mặt khi đứng lên"], optionA: ["keep the person seated and call first aid", "để người đó ngồi và gọi sơ cứu"], optionB: ["ask someone to clear the busy area", "nhờ ai đó dọn khoảng trống quanh khu vực"], result: ["trained help arrives and further harm is avoided", "nhân viên được đào tạo đến và tránh được tổn thương thêm"], value: ["calm coordination is safer than rushed action", "phối hợp bình tĩnh an toàn hơn hành động vội vàng"], sourceBasis: "DRAL" },
  { id: "celebration", title: ["Planning an Inclusive Celebration", "Lập kế hoạch lễ kỷ niệm hòa nhập"], topic: ["celebrations and traditions", "lễ kỷ niệm và truyền thống"], place: ["during a family planning call", "trong cuộc gọi lập kế hoạch gia đình"], need: ["plan a celebration that everyone can join", "lên kế hoạch lễ kỷ niệm mọi người đều tham gia được"], obstacle: ["some relatives cannot travel far", "một số người thân không thể đi xa"], optionA: ["hold a smaller local gathering", "tổ chức buổi gặp nhỏ tại địa phương"], optionB: ["include a short online part", "thêm một phần trực tuyến ngắn"], result: ["people feel included without an exhausting schedule", "mọi người cảm thấy được tham gia mà lịch trình không mệt mỏi"], value: ["tradition stays meaningful when it responds to people", "truyền thống giữ được ý nghĩa khi đáp ứng con người"], sourceBasis: "DRAL" },
  { id: "nature", title: ["A Responsible Day Outdoors", "Một ngày ngoài trời có trách nhiệm"], topic: ["nature and outdoor activities", "thiên nhiên và hoạt động ngoài trời"], place: ["while planning a walk", "khi lên kế hoạch đi bộ"], need: ["enjoy a protected natural area", "tận hưởng một khu thiên nhiên được bảo vệ"], obstacle: ["one popular path is closed for restoration", "một lối đi nổi tiếng đóng cửa để phục hồi"], optionA: ["take the marked alternative route", "đi tuyến thay thế có đánh dấu"], optionB: ["visit a less sensitive area", "tham quan khu vực ít nhạy cảm hơn"], result: ["the group enjoys the day without damaging the site", "cả nhóm tận hưởng ngày đi chơi mà không làm hại địa điểm"], value: ["access to nature comes with shared responsibility", "tiếp cận thiên nhiên đi cùng trách nhiệm chung"], sourceBasis: "DRAL" },
  { id: "creative-hobby", title: ["Starting a Creative Hobby", "Bắt đầu một sở thích sáng tạo"], topic: ["hobbies and creativity", "sở thích và sáng tạo"], place: ["at a community arts centre", "tại trung tâm nghệ thuật cộng đồng"], need: ["choose a beginner-friendly class", "chọn lớp phù hợp người mới"], obstacle: ["the most popular class is already full", "lớp phổ biến nhất đã đủ chỗ"], optionA: ["join a smaller drawing workshop", "tham gia lớp vẽ nhỏ hơn"], optionB: ["try the photography class", "thử lớp nhiếp ảnh"], result: ["the learner begins creating instead of waiting", "người học bắt đầu sáng tạo thay vì chờ đợi"], value: ["progress often begins with a workable opportunity", "tiến bộ thường bắt đầu từ cơ hội khả thi"], sourceBasis: "Taskmaster" },
  { id: "language-learning", title: ["Practising a Language Every Day", "Luyện ngôn ngữ mỗi ngày"], topic: ["language learning", "học ngôn ngữ"], place: ["during a study-partner conversation", "trong cuộc trò chuyện với bạn học"], need: ["speak English more consistently", "nói tiếng Anh đều đặn hơn"], obstacle: ["long study sessions are difficult to maintain", "các buổi học dài khó duy trì"], optionA: ["practise one short dialogue each morning", "luyện một hội thoại ngắn mỗi sáng"], optionB: ["record a one-minute reflection at night", "ghi âm suy nghĩ một phút vào buổi tối"], result: ["practice becomes regular and measurable", "việc luyện tập trở nên đều đặn và đo lường được"], value: ["frequency and reflection matter more than occasional intensity", "tần suất và suy ngẫm quan trọng hơn cường độ thỉnh thoảng"], sourceBasis: "DRAL" },
  { id: "news", title: ["Discussing a News Story Carefully", "Thảo luận tin tức cẩn trọng"], topic: ["news and information", "tin tức và thông tin"], place: ["during a conversation with friends", "trong cuộc trò chuyện với bạn bè"], need: ["understand a widely shared news story", "hiểu một tin tức được chia sẻ rộng rãi"], obstacle: ["the headline makes a stronger claim than the article", "tiêu đề đưa ra tuyên bố mạnh hơn bài viết"], optionA: ["read the original source", "đọc nguồn gốc"], optionB: ["compare reporting from another outlet", "so sánh bài đưa tin từ một đơn vị khác"], result: ["the group forms a more accurate view", "cả nhóm hình thành góc nhìn chính xác hơn"], value: ["responsible discussion separates evidence from reaction", "thảo luận có trách nhiệm tách bằng chứng khỏi phản ứng"], sourceBasis: "DRAL" },
];

const variants = [
  { id: "core", en: "Core exchange", vi: "Hội thoại cốt lõi", listen: "Xác định nhu cầu, trở ngại và kết quả.", speak: "Đóng vai lại tình huống và thay đổi một chi tiết." },
  { id: "clarify", en: "Clarifying details", vi: "Làm rõ thông tin", listen: "Ghi lại câu hỏi làm rõ và thông tin được xác nhận.", speak: "Dùng câu hỏi tiếp nối để kiểm tra bạn đã hiểu đúng." },
  { id: "compare", en: "Comparing options", vi: "So sánh lựa chọn", listen: "Nghe hai phương án và lý do chọn phương án cuối.", speak: "So sánh hai lựa chọn rồi nêu quyết định của bạn." },
  { id: "problem", en: "Solving the problem", vi: "Giải quyết vấn đề", listen: "Sắp xếp vấn đề, hành động và kết quả theo đúng thứ tự.", speak: "Giải thích cách bạn sẽ xử lý tình huống tương tự." },
  { id: "reflect", en: "Reflecting on the lesson", vi: "Rút ra bài học", listen: "Nghe ý nghĩa rộng hơn được rút ra từ tình huống.", speak: "Nêu bài học và liên hệ với một trải nghiệm thật của bạn." },
  { id: "repair", en: "Repairing misunderstanding", vi: "Sửa hiểu lầm", listen: "Tìm chỗ hai người hiểu khác nhau và cách họ làm rõ.", speak: "Luyện cách sửa hiểu lầm mà vẫn giữ thái độ lịch sự." },
  { id: "roleplay", en: "Natural role-play", vi: "Đóng vai tự nhiên", listen: "Xác định vai trò, mục tiêu và phản hồi tự nhiên của hai người.", speak: "Đóng vai cả hai phía và thay đổi kết quả cuối." },
  { id: "personalise", en: "Personal response", vi: "Phản hồi cá nhân", listen: "Nghe cách người nói liên hệ tình huống với nhu cầu riêng.", speak: "Biến hội thoại thành câu chuyện thật trong cuộc sống của bạn." },
] as const;

const bands: Array<{ stageId: StageId; level: string; target: number }> = [
  { stageId: "beginner", level: "A0-Pre A1", target: 281 },
  { stageId: "elementary", level: "A1", target: 281 },
  { stageId: "pre-intermediate", level: "A2", target: 281 },
  { stageId: "intermediate", level: "B1", target: 281 },
  { stageId: "upper-intermediate", level: "B2", target: 281 },
  { stageId: "advanced", level: "C1", target: 280 },
  { stageId: "proficient", level: "C2", target: 280 },
];

const l = (speaker: "female" | "male", en: string, vi: string): DialogueLine => ({ speaker, en, vi });

function variantExchange(s: Scenario, stageId: StageId, variantIndex: number): DialogueLine[] {
  const simple = stageId === "beginner" || stageId === "elementary";
  const advanced = stageId === "advanced" || stageId === "proficient";
  const exchanges: DialogueLine[][] = simple ? [
    [l("male", "What do we need to do?", "Chúng ta cần làm gì?"), l("female", `We need to ${s.need[0]}.`, `Chúng ta cần ${s.need[1]}.`)],
    [l("male", `Do you mean we should ${s.optionA[0]}?`, `Ý bạn là chúng ta nên ${s.optionA[1]} phải không?`), l("female", "Yes, that is what I mean.", "Đúng, ý tôi là như vậy.")],
    [l("male", "Do we have another choice?", "Chúng ta có lựa chọn khác không?"), l("female", `Yes. We can also ${s.optionB[0]}.`, `Có. Chúng ta cũng có thể ${s.optionB[1]}.`)],
    [l("male", "What is the problem?", "Vấn đề là gì?"), l("female", `The problem is that ${s.obstacle[0]}.`, `Vấn đề là ${s.obstacle[1]}.`)],
    [l("male", "What did we learn?", "Chúng ta đã học được gì?"), l("female", "A clear plan can help.", "Một kế hoạch rõ ràng có thể giúp ích.")],
    [l("male", "Sorry, did I understand you correctly?", "Xin lỗi, tôi đã hiểu đúng ý bạn chưa?"), l("female", `Almost. I said we could ${s.optionB[0]}.`, `Gần đúng. Tôi nói rằng chúng ta có thể ${s.optionB[1]}.`)],
    [l("male", "I will ask, and you can answer.", "Tôi sẽ hỏi và bạn có thể trả lời."), l("female", "All right. Let’s begin.", "Được. Chúng ta bắt đầu nhé.")],
    [l("male", "What would you choose?", "Bạn sẽ chọn gì?"), l("female", `I would ${s.optionA[0]}.`, `Tôi sẽ ${s.optionA[1]}.`)],
  ] : advanced ? [
    [l("male", "Before considering solutions, how would you define the central issue?", "Trước khi cân nhắc giải pháp, bạn sẽ xác định vấn đề cốt lõi thế nào?"), l("female", `The central issue is how to ${s.need[0]} without overlooking the fact that ${s.obstacle[0]}.`, `Vấn đề cốt lõi là làm sao ${s.need[1]} mà không bỏ qua việc ${s.obstacle[1]}.`)],
    [l("male", "When you describe that as practical, which criterion are you using?", "Khi gọi cách đó là thực tế, bạn đang dùng tiêu chí nào?"), l("female", `I mean that it should lead to this outcome: ${s.result[0]}.`, `Ý tôi là cách đó nên dẫn đến kết quả này: ${s.result[1]}.`)],
    [l("male", "How do the alternatives differ beyond their immediate convenience?", "Các phương án khác nhau thế nào ngoài sự thuận tiện trước mắt?"), l("female", `To ${s.optionA[0]} prioritises certainty, whereas choosing to ${s.optionB[0]} preserves more flexibility.`, `Việc ${s.optionA[1]} ưu tiên sự chắc chắn, trong khi chọn ${s.optionB[1]} giữ được nhiều linh hoạt hơn.`)],
    [l("male", "Which obstacle must be addressed before either option can work?", "Trở ngại nào phải được xử lý trước khi bất kỳ phương án nào có hiệu quả?"), l("female", `We first need to address the fact that ${s.obstacle[0]}.`, `Trước tiên chúng ta cần xử lý việc ${s.obstacle[1]}.`)],
    [l("male", "What broader lesson can reasonably be drawn from this case?", "Có thể rút ra bài học rộng hơn nào một cách hợp lý từ trường hợp này?"), l("female", `It suggests that ${s.value[0]}, although the lesson should still be applied with regard to context.`, `Trường hợp này cho thấy ${s.value[1]}, dù bài học vẫn cần được áp dụng có xét đến hoàn cảnh.`)],
    [l("male", "I may have interpreted your recommendation as a fixed rule. Was that your intention?", "Có lẽ tôi đã hiểu khuyến nghị của bạn như một quy tắc cố định. Đó có phải ý bạn không?"), l("female", "No. I was proposing a context-sensitive choice, not a rule that should apply everywhere.", "Không. Tôi đề xuất một lựa chọn phù hợp bối cảnh, không phải quy tắc áp dụng ở mọi nơi.")],
    [l("male", "Let me challenge the proposal from the other side so that we can test it properly.", "Để tôi phản biện đề xuất từ phía đối diện để chúng ta kiểm tra nó kỹ hơn."), l("female", "Please do. A credible proposal should be able to withstand a fair objection.", "Xin cứ làm vậy. Một đề xuất đáng tin phải chịu được phản biện công bằng.")],
    [l("male", "How would your own circumstances affect this decision?", "Hoàn cảnh riêng của bạn sẽ ảnh hưởng quyết định này thế nào?"), l("female", `I would favour the option that helps achieve the intended result—${s.result[0]}—without shifting an unreasonable burden to someone else.`, `Tôi sẽ nghiêng về phương án giúp đạt kết quả mong muốn—${s.result[1]}—mà không chuyển gánh nặng bất hợp lý sang người khác.`)],
  ] : [
    [l("male", "What is the main outcome we are trying to achieve?", "Kết quả chính chúng ta muốn đạt được là gì?"), l("female", `The aim is to ${s.need[0]} and, ultimately, ensure that ${s.result[0]}.`, `Mục tiêu là ${s.need[1]} và cuối cùng bảo đảm rằng ${s.result[1]}.`)],
    [l("male", "Could you clarify what makes the original plan difficult?", "Bạn có thể làm rõ điều gì khiến kế hoạch ban đầu khó thực hiện không?"), l("female", `Certainly. The difficulty is that ${s.obstacle[0]}.`, `Được. Khó khăn là ${s.obstacle[1]}.`)],
    [l("male", "How would you compare the two realistic options?", "Bạn sẽ so sánh hai phương án thực tế thế nào?"), l("female", `We can either ${s.optionA[0]} or ${s.optionB[0]}; each solves a different part of the problem.`, `Chúng ta có thể ${s.optionA[1]} hoặc ${s.optionB[1]}; mỗi cách giải quyết một phần khác nhau của vấn đề.`)],
    [l("male", "What should we deal with first?", "Chúng ta nên xử lý điều gì trước?"), l("female", `First, we should respond directly to the fact that ${s.obstacle[0]}.`, `Trước tiên, chúng ta nên xử lý trực tiếp việc ${s.obstacle[1]}.`)],
    [l("male", "What lesson would you carry into a similar situation?", "Bạn sẽ mang bài học nào sang tình huống tương tự?"), l("female", `I would remember that ${s.value[0]}.`, `Tôi sẽ nhớ rằng ${s.value[1]}.`)],
    [l("male", "I thought you preferred the first option. Have I misunderstood?", "Tôi nghĩ bạn thích phương án đầu. Tôi đã hiểu nhầm phải không?"), l("female", `A little. I prefer to ${s.optionB[0]} in this particular situation.`, `Một chút. Trong tình huống cụ thể này, tôi muốn ${s.optionB[1]}.`)],
    [l("male", "Shall we switch roles and test both sides of the conversation?", "Chúng ta đổi vai và thử cả hai phía của cuộc hội thoại nhé?"), l("female", "Yes. That will help us respond instead of memorising one answer.", "Được. Cách đó giúp chúng ta phản hồi thay vì ghi nhớ một câu trả lời.")],
    [l("male", "Which option fits your own life more closely?", "Phương án nào phù hợp hơn với cuộc sống của bạn?"), l("female", `For me, it would be more realistic to ${s.optionA[0]}, but I would review the result afterwards.`, `Với tôi, ${s.optionA[1]} sẽ thực tế hơn, nhưng sau đó tôi sẽ xem lại kết quả.`)],
  ];
  return exchanges[variantIndex];
}

function makeLines(s: Scenario, stageId: StageId, variantIndex: number): DialogueLine[] {
  const extra = variantIndex % 2 === 0 ? s.optionA : s.optionB;
  const moves: Pair[] = [
    ["Let’s first understand the main situation.", "Trước tiên hãy hiểu tình huống chính."],
    ["Let’s confirm the details before deciding.", "Hãy xác nhận chi tiết trước khi quyết định."],
    ["Let’s compare the available choices carefully.", "Hãy so sánh kỹ các lựa chọn hiện có."],
    ["Let’s solve the immediate problem step by step.", "Hãy giải quyết vấn đề trước mắt từng bước một."],
    ["Let’s also consider what this situation teaches us.", "Hãy cùng cân nhắc điều tình huống này dạy chúng ta."],
    ["Let’s check whether we have understood each other correctly.", "Hãy kiểm tra xem chúng ta đã hiểu nhau đúng chưa."],
    ["Let’s respond as naturally as we would in real life.", "Hãy phản hồi tự nhiên như trong đời thực."],
    ["Let’s connect this situation to our own experience.", "Hãy liên hệ tình huống này với trải nghiệm của chúng ta."],
  ];
  const move = moves[variantIndex];
  const shape = (lines: DialogueLine[]) => [lines[0], ...variantExchange(s, stageId, variantIndex), ...lines.slice(3)];
  if (stageId === "beginner") return shape([
    l("female", `Hello. I need to ${s.need[0]}. ${move[0]}`, `Xin chào. Tôi cần ${s.need[1]}. ${move[1]}`),
    l("male", `Okay. We are ${s.place[0]}.`, `Được. Chúng ta đang ${s.place[1]}.`),
    l("female", `Can we ${extra[0]}?`, `Chúng ta có thể ${extra[1]} không?`),
    l("male", `Yes. That is a good plan.`, `Có. Đó là một kế hoạch tốt.`),
    l("female", `Great. Let’s do it.`, `Tuyệt. Chúng ta làm nhé.`),
  ]);
  if (stageId === "elementary") return shape([
    l("female", `Excuse me. I want to ${s.need[0]}. ${move[0]}`, `Xin lỗi. Tôi muốn ${s.need[1]}. ${move[1]}`),
    l("male", `Of course. What is the problem?`, `Được chứ. Vấn đề là gì?`),
    l("female", `The problem is that ${s.obstacle[0]}.`, `Vấn đề là ${s.obstacle[1]}.`),
    l("male", `Would you like to ${extra[0]}?`, `Bạn có muốn ${extra[1]} không?`),
    l("female", `Yes, please. Does that work?`, `Có. Như vậy có được không?`),
    l("male", `Yes. It will help us ${s.result[0]}.`, `Được. Việc đó sẽ giúp ${s.result[1]}.`),
  ]);
  if (stageId === "pre-intermediate") return shape([
    l("female", `We need to ${s.need[0]}, but ${s.obstacle[0]}. ${move[0]}`, `Chúng ta cần ${s.need[1]}, nhưng ${s.obstacle[1]}. ${move[1]}`),
    l("male", `Why don’t we ${s.optionA[0]}?`, `Sao chúng ta không ${s.optionA[1]}?`),
    l("female", `That could work. Another idea is to ${s.optionB[0]}.`, `Cách đó có thể được. Một ý khác là ${s.optionB[1]}.`),
    l("male", `Which option is easier today?`, `Hôm nay phương án nào dễ hơn?`),
    l("female", `I prefer to ${extra[0]} because it fits our situation.`, `Tôi muốn ${extra[1]} vì phù hợp với tình huống của chúng ta.`),
    l("male", `Good. Then we can ${s.result[0]}.`, `Tốt. Vậy chúng ta có thể ${s.result[1]}.`),
  ]);
  if (stageId === "intermediate") return shape([
    l("female", `I ran into a problem ${s.place[0]} while trying to ${s.need[0]}. ${move[0]}`, `Tôi gặp một vấn đề ${s.place[1]} khi cố ${s.need[1]}. ${move[1]}`),
    l("male", `What made the situation difficult?`, `Điều gì khiến tình huống trở nên khó khăn?`),
    l("female", `${s.obstacle[0]}, so my original plan no longer worked.`, `${s.obstacle[1]}, nên kế hoạch ban đầu của tôi không còn hiệu quả.`),
    l("male", `Did you consider both available options?`, `Bạn đã cân nhắc cả hai phương án chưa?`),
    l("female", `Yes. I could ${s.optionA[0]}, or I could ${s.optionB[0]}.`, `Rồi. Tôi có thể ${s.optionA[1]}, hoặc ${s.optionB[1]}.`),
    l("male", `What did you decide?`, `Bạn đã quyết định thế nào?`),
    l("female", `I chose to ${extra[0]}. As a result, ${s.result[0]}.`, `Tôi chọn ${extra[1]}. Nhờ vậy, ${s.result[1]}.`),
    l("male", `That shows why ${s.value[0]}.`, `Điều đó cho thấy vì sao ${s.value[1]}.`),
  ]);
  if (stageId === "upper-intermediate") return shape([
    l("female", `We need a practical way to ${s.need[0]}, given that ${s.obstacle[0]}. ${move[0]}`, `Chúng ta cần một cách thực tế để ${s.need[1]}, trong khi ${s.obstacle[1]}. ${move[1]}`),
    l("male", `The first option is to ${s.optionA[0]}. What is the alternative?`, `Phương án đầu là ${s.optionA[1]}. Phương án thay thế là gì?`),
    l("female", `We could also ${s.optionB[0]}. It may involve a different trade-off.`, `Chúng ta cũng có thể ${s.optionB[1]}. Cách đó có thể có đánh đổi khác.`),
    l("male", `Which option would you recommend, and on what grounds?`, `Bạn khuyên chọn phương án nào và dựa trên cơ sở gì?`),
    l("female", `I would ${extra[0]} because it offers the clearest path forward. If it works, ${s.result[0]}.`, `Tôi sẽ ${extra[1]} vì đó là hướng đi rõ ràng nhất. Nếu hiệu quả, ${s.result[1]}.`),
    l("male", `Is there a disadvantage we should acknowledge?`, `Có bất lợi nào chúng ta nên thừa nhận không?`),
    l("female", `Yes, but the disadvantage is manageable if we communicate clearly.`, `Có, nhưng bất lợi đó có thể xử lý nếu chúng ta giao tiếp rõ ràng.`),
    l("male", `Then the recommendation is balanced rather than automatic.`, `Vậy khuyến nghị này cân bằng chứ không máy móc.`),
  ]);
  if (stageId === "advanced") return shape([
    l("female", `At first glance, the aim to ${s.need[0]} seems straightforward. ${move[0]}`, `Thoạt nhìn, mục tiêu ${s.need[1]} có vẻ đơn giản. ${move[1]}`),
    l("male", `Yet the fact that ${s.obstacle[0]} complicates the decision.`, `Tuy nhiên, việc ${s.obstacle[1]} khiến quyết định phức tạp hơn.`),
    l("female", `Exactly. We could ${s.optionA[0]}, which prioritises immediate practicality.`, `Chính xác. Ta có thể ${s.optionA[1]}, cách này ưu tiên tính thực tế trước mắt.`),
    l("male", `Whereas choosing to ${s.optionB[0]} may protect a different interest.`, `Trong khi chọn ${s.optionB[1]} có thể bảo vệ một lợi ích khác.`),
    l("female", `My preference is to ${extra[0]}, though I would not present it as risk-free.`, `Tôi thiên về ${extra[1]}, dù tôi sẽ không nói rằng cách đó không có rủi ro.`),
    l("male", `What evidence would make you revise that preference?`, `Bằng chứng nào sẽ khiến bạn thay đổi lựa chọn đó?`),
    l("female", `I would reconsider if the choice no longer led to the intended outcome—${s.result[0]}—or if it imposed hidden costs on others.`, `Tôi sẽ cân nhắc lại nếu lựa chọn không còn dẫn đến kết quả mong muốn—${s.result[1]}—hoặc tạo chi phí ẩn cho người khác.`),
    l("male", `That condition makes the proposal more accountable.`, `Điều kiện đó khiến đề xuất có trách nhiệm giải trình hơn.`),
    l("female", `More broadly, the case illustrates that ${s.value[0]}.`, `Rộng hơn, trường hợp này cho thấy ${s.value[1]}.`),
  ]);
  return shape([
    l("female", `The apparent simplicity of trying to ${s.need[0]} conceals a question of judgment. ${move[0]}`, `Sự đơn giản bề ngoài của việc ${s.need[1]} che giấu một câu hỏi về phán đoán. ${move[1]}`),
    l("male", `Particularly because ${s.obstacle[0]}; no option is neutral once the consequences are considered.`, `Đặc biệt vì ${s.obstacle[1]}; không phương án nào trung lập khi xét đến hệ quả.`),
    l("female", `We might ${s.optionA[0]}, although that privileges certainty and immediate control.`, `Ta có thể ${s.optionA[1]}, dù cách đó ưu tiên sự chắc chắn và kiểm soát trước mắt.`),
    l("male", `Alternatively, we could ${s.optionB[0]}, accepting ambiguity in exchange for flexibility.`, `Hoặc ta có thể ${s.optionB[1]}, chấp nhận mơ hồ để đổi lấy linh hoạt.`),
    l("female", `I lean toward the latter in this context, but I would resist turning that preference into a universal rule.`, `Trong bối cảnh này tôi nghiêng về phương án sau, nhưng không muốn biến lựa chọn đó thành quy tắc phổ quát.`),
    l("male", `That qualification matters. What would responsible implementation require?`, `Giới hạn đó quan trọng. Việc triển khai có trách nhiệm đòi hỏi điều gì?`),
    l("female", `Clear ownership, a review point, and an explicit test of the intended outcome: did we reach a point where ${s.result[0]}?`, `Cần trách nhiệm rõ ràng, thời điểm xem xét lại và phép thử cụ thể cho kết quả mong muốn: chúng ta đã đạt đến trạng thái ${s.result[1]} chưa?`),
    l("male", `So revision would represent learning rather than failure.`, `Vậy điều chỉnh sẽ thể hiện việc học hỏi chứ không phải thất bại.`),
    l("female", `Precisely. It also respects the broader principle that ${s.value[0]}.`, `Chính xác. Cách đó cũng tôn trọng nguyên tắc rộng hơn rằng ${s.value[1]}.`),
    l("male", `That gives us a decision we can defend without pretending the uncertainty has disappeared.`, `Như vậy ta có quyết định có thể bảo vệ mà không giả vờ rằng sự không chắc chắn đã biến mất.`),
  ]);
}

export const expandedTopics: DialogueLesson[] = bands.flatMap((band, bandIndex) =>
  Array.from({ length: band.target }, (_, index) => {
    const scenario = scenarios[(index + bandIndex * 3) % scenarios.length];
    const variantIndex = Math.floor(index / scenarios.length) % variants.length;
    const variant = variants[variantIndex];
    return {
      id: `expanded-${band.stageId}-${scenario.id}-${variant.id}`,
      en: `${scenario.title[0]} — ${variant.en}`,
      vi: `${scenario.title[1]} — ${variant.vi}`,
      baseTopic: scenario.topic[1],
      level: band.level,
      stageId: band.stageId,
      variant: variant.vi,
      lines: makeLines(scenario, band.stageId, variantIndex),
      listenTask: `${variant.listen} Bối cảnh: ${scenario.place[1]}.`,
      speakTask: `${variant.speak} Mục tiêu: ${scenario.need[1]}.`,
      sourceBasis: scenario.sourceBasis,
    };
  }),
);

const expandedIds = new Set(expandedTopics.map((topic) => topic.id));
const expandedTranscripts = new Set(
  expandedTopics.map((topic) => topic.lines.map((dialogueLine) => dialogueLine.en).join(" ").toLowerCase()),
);
if (expandedTopics.length !== 1965 || expandedIds.size !== 1965 || expandedTranscripts.size !== 1965) {
  throw new Error("Expanded dialogue corpus failed count or uniqueness validation.");
}
