export type DialogueLine = {
  speaker: "female" | "male";
  en: string;
  vi: string;
};

export type DialogueLesson = {
  id: string;
  en: string;
  vi: string;
  baseTopic: string;
  level: string;
  stageId: "beginner" | "elementary" | "pre-intermediate" | "intermediate" | "upper-intermediate" | "advanced" | "proficient";
  variant: string;
  lines: DialogueLine[];
  listenTask: string;
  speakTask: string;
  sourceBasis?: "Taskmaster" | "MultiWOZ" | "Schema-Guided Dialogue" | "DRAL" | "Biên soạn gốc";
};

const line = (speaker: "female" | "male", en: string, vi: string): DialogueLine => ({ speaker, en, vi });

export const topics: DialogueLesson[] = [
  {
    id: "beginner-hello-neighbour", en: "Hello, New Neighbour", vi: "Chào người hàng xóm mới", baseTopic: "Chào hỏi", level: "A0-Pre A1", stageId: "beginner", variant: "Hội thoại cốt lõi",
    lines: [line("female", "Hello. I’m Mai.", "Xin chào. Mình là Mai."), line("male", "Hi, Mai. I’m Ben.", "Chào Mai. Mình là Ben."), line("female", "Are you new here?", "Bạn mới đến đây phải không?"), line("male", "Yes, I am. Nice to meet you.", "Đúng vậy. Rất vui được gặp bạn."), line("female", "Nice to meet you too.", "Mình cũng rất vui được gặp bạn.")],
    listenTask: "Nghe tên của hai người và xác định ai là người mới.", speakTask: "Đổi tên nhân vật thành tên của bạn và chào một người mới."
  },
  {
    id: "beginner-breakfast", en: "Tea or Milk?", vi: "Trà hay sữa?", baseTopic: "Bữa sáng", level: "A0-Pre A1", stageId: "beginner", variant: "Lựa chọn đơn giản",
    lines: [line("female", "Good morning, Dad.", "Chào buổi sáng, bố."), line("male", "Good morning. Tea or milk?", "Chào buổi sáng. Con uống trà hay sữa?"), line("female", "Milk, please.", "Cho con sữa ạ."), line("male", "Here you are.", "Của con đây."), line("female", "Thank you.", "Con cảm ơn bố.")],
    listenTask: "Nghe và chọn đồ uống mà người con muốn.", speakTask: "Thay milk bằng một đồ uống bạn thích."
  },
  {
    id: "beginner-classroom", en: "My Blue Pencil", vi: "Bút chì màu xanh của em", baseTopic: "Trong lớp học", level: "A0-Pre A1", stageId: "beginner", variant: "Nhận biết đồ vật",
    lines: [line("female", "Is this your pencil?", "Đây là bút chì của em phải không?"), line("male", "No. My pencil is blue.", "Không ạ. Bút chì của em màu xanh."), line("female", "Is this blue one yours?", "Cây màu xanh này là của em phải không?"), line("male", "Yes, it is. Thank you.", "Đúng rồi ạ. Em cảm ơn cô.")],
    listenTask: "Nghe màu của chiếc bút chì cần tìm.", speakTask: "Đổi pencil và blue thành một đồ vật và màu khác."
  },
  {
    id: "beginner-bus", en: "The Bus to School", vi: "Xe buýt đến trường", baseTopic: "Đi xe buýt", level: "A0-Pre A1", stageId: "beginner", variant: "Hỏi có/không",
    lines: [line("female", "Excuse me. Is this bus number six?", "Xin lỗi. Đây có phải xe buýt số 6 không?"), line("male", "Yes, it is.", "Đúng rồi."), line("female", "Does it go to Green School?", "Xe có đến Trường Green không?"), line("male", "Yes. Please get on.", "Có. Mời bạn lên xe."), line("female", "Thank you.", "Cảm ơn bác.")],
    listenTask: "Nghe số xe và điểm đến.", speakTask: "Hỏi về một số xe và địa điểm khác."
  },
  {
    id: "beginner-helping-home", en: "Setting the Table", vi: "Dọn bàn ăn", baseTopic: "Giúp việc nhà", level: "A0-Pre A1", stageId: "beginner", variant: "Đề nghị giúp đỡ",
    lines: [line("female", "Can I help, Mum?", "Con giúp mẹ được không?"), line("male", "Yes, please. Put these cups on the table.", "Được chứ. Con đặt những chiếc cốc này lên bàn nhé."), line("female", "Here?", "Ở đây ạ?"), line("male", "Yes. That’s perfect.", "Đúng rồi. Như vậy rất tốt."), line("female", "All done!", "Xong rồi ạ!")],
    listenTask: "Nghe xem đồ vật nào được đặt lên bàn.", speakTask: "Đề nghị giúp một việc nhỏ trong nhà."
  },

  {
    id: "elementary-library-card", en: "A Library Card", vi: "Làm thẻ thư viện", baseTopic: "Thư viện", level: "A1", stageId: "elementary", variant: "Hỏi thông tin",
    lines: [line("female", "Hello. I’d like a library card, please.", "Xin chào. Tôi muốn làm thẻ thư viện."), line("male", "Of course. What’s your name?", "Được chứ. Bạn tên là gì?"), line("female", "My name is Lan Nguyen.", "Tôi tên là Lan Nguyễn."), line("male", "What’s your address?", "Địa chỉ của bạn là gì?"), line("female", "It’s 25 Lake Street.", "Đó là số 25 đường Lake."), line("male", "Thank you. Your card is ready.", "Cảm ơn bạn. Thẻ của bạn đã xong.")],
    listenTask: "Ghi lại tên và địa chỉ của người đăng ký.", speakTask: "Đóng vai người đăng ký và cung cấp thông tin của bạn."
  },
  {
    id: "elementary-lunch-order", en: "Ordering Lunch", vi: "Gọi món trưa", baseTopic: "Nhà hàng", level: "A1", stageId: "elementary", variant: "Gọi món lịch sự",
    lines: [line("female", "Are you ready to order?", "Bạn đã sẵn sàng gọi món chưa?"), line("male", "Yes. I’d like the chicken soup, please.", "Rồi. Cho tôi súp gà."), line("female", "Would you like bread with it?", "Bạn có muốn dùng kèm bánh mì không?"), line("male", "Yes, please. And a glass of water.", "Có. Và cho tôi một cốc nước."), line("female", "Certainly. I’ll bring it soon.", "Vâng. Tôi sẽ mang ra ngay.")],
    listenTask: "Nghe và liệt kê món ăn, đồ uống được gọi.", speakTask: "Gọi một bữa trưa đơn giản bằng I’d like..."
  },
  {
    id: "elementary-weekend", en: "A Saturday Plan", vi: "Kế hoạch thứ Bảy", baseTopic: "Cuối tuần", level: "A1", stageId: "elementary", variant: "Mời và trả lời",
    lines: [line("female", "Are you free on Saturday?", "Bạn có rảnh vào thứ Bảy không?"), line("male", "Yes, I am. Why?", "Có. Sao vậy?"), line("female", "Would you like to go to the park?", "Bạn có muốn đi công viên không?"), line("male", "That sounds nice. What time?", "Nghe hay đấy. Mấy giờ?"), line("female", "Let’s meet at nine.", "Chúng ta gặp nhau lúc 9 giờ nhé."), line("male", "Great. See you then.", "Tuyệt. Hẹn gặp bạn lúc đó.")],
    listenTask: "Nghe ngày, địa điểm và giờ hẹn.", speakTask: "Mời một người bạn đi chơi và thống nhất thời gian."
  },
  {
    id: "elementary-directions", en: "Where Is the Pharmacy?", vi: "Hiệu thuốc ở đâu?", baseTopic: "Hỏi đường", level: "A1", stageId: "elementary", variant: "Chỉ đường ngắn",
    lines: [line("female", "Excuse me. Where is the pharmacy?", "Xin lỗi. Hiệu thuốc ở đâu vậy?"), line("male", "Go straight to the traffic lights.", "Đi thẳng đến đèn giao thông."), line("female", "Do I turn left there?", "Tôi rẽ trái ở đó phải không?"), line("male", "Yes. It’s next to the bank.", "Đúng. Nó ở cạnh ngân hàng."), line("female", "Thank you for your help.", "Cảm ơn bạn đã giúp.")],
    listenTask: "Nghe các mốc chỉ đường theo đúng thứ tự.", speakTask: "Chỉ đường đến một nơi gần nhà bạn."
  },
  {
    id: "elementary-missed-word", en: "Could You Say That Again?", vi: "Bạn có thể nói lại không?", baseTopic: "Kiểm tra sự hiểu", level: "A1", stageId: "elementary", variant: "Yêu cầu nhắc lại",
    lines: [line("female", "Please bring your workbook tomorrow.", "Ngày mai em hãy mang theo sách bài tập."), line("male", "Sorry, could you say that again?", "Xin lỗi, cô có thể nói lại không ạ?"), line("female", "Bring your workbook tomorrow.", "Ngày mai mang theo sách bài tập nhé."), line("male", "My workbook, not my textbook. Is that right?", "Sách bài tập, không phải sách giáo khoa. Đúng không ạ?"), line("female", "That’s right.", "Đúng rồi.")],
    listenTask: "Nghe đồ vật cần mang theo và thời gian.", speakTask: "Luyện hai câu: Could you say that again? và Is that right?"
  },

  {
    id: "pre-intermediate-new-colleague", en: "A New Colleague", vi: "Đồng nghiệp mới", baseTopic: "Công việc", level: "A2", stageId: "pre-intermediate", variant: "Thể hiện quan tâm",
    lines: [line("female", "How was your first morning here?", "Buổi sáng đầu tiên của bạn ở đây thế nào?"), line("male", "Good, but there’s a lot to remember.", "Tốt, nhưng có khá nhiều điều phải nhớ."), line("female", "I felt the same in my first week.", "Tuần đầu tiên tôi cũng cảm thấy như vậy."), line("male", "Really? How did you learn everything?", "Thật sao? Bạn đã học mọi thứ như thế nào?"), line("female", "I kept a short list and asked one question at a time.", "Tôi ghi một danh sách ngắn và hỏi từng câu một."), line("male", "That’s a useful idea. I’ll try it.", "Ý đó hữu ích đấy. Tôi sẽ thử.")],
    listenTask: "Nghe khó khăn và lời khuyên dành cho nhân viên mới.", speakTask: "Hỏi tiếp để thể hiện quan tâm và đưa một lời khuyên đơn giản."
  },
  {
    id: "pre-intermediate-study-plan", en: "Planning for the Test", vi: "Lập kế hoạch ôn thi", baseTopic: "Học tập", level: "A2", stageId: "pre-intermediate", variant: "Đưa gợi ý",
    lines: [line("female", "The science test is next Friday.", "Bài kiểm tra khoa học vào thứ Sáu tuần sau."), line("male", "I know. I haven’t started studying yet.", "Mình biết. Mình vẫn chưa bắt đầu ôn."), line("female", "Why don’t we study together after school?", "Sao chúng ta không học cùng nhau sau giờ học?"), line("male", "Good idea. Tuesday is best for me.", "Ý hay. Thứ Ba phù hợp nhất với mình."), line("female", "Let’s review two chapters and quiz each other.", "Chúng ta ôn hai chương rồi hỏi bài nhau nhé."), line("male", "Great. That feels manageable.", "Tuyệt. Như vậy có vẻ vừa sức.")],
    listenTask: "Nghe ngày thi, ngày học nhóm và hai hoạt động ôn tập.", speakTask: "Dùng Why don’t we...? để đề xuất một kế hoạch học tập."
  },
  {
    id: "pre-intermediate-return-shirt", en: "Returning a Shirt", vi: "Đổi trả áo sơ mi", baseTopic: "Mua sắm", level: "A2", stageId: "pre-intermediate", variant: "Giải thích vấn đề",
    lines: [line("female", "Hello. I’d like to return this shirt.", "Xin chào. Tôi muốn trả lại chiếc áo này."), line("male", "Is there a problem with it?", "Chiếc áo có vấn đề gì không?"), line("female", "It’s too small, although I bought my usual size.", "Nó quá nhỏ, dù tôi đã mua cỡ thường mặc."), line("male", "Would you like a larger one or a refund?", "Bạn muốn đổi chiếc lớn hơn hay hoàn tiền?"), line("female", "A larger one, please. I like the colour.", "Cho tôi chiếc lớn hơn. Tôi thích màu này."), line("male", "No problem. I’ll check for your size.", "Không vấn đề gì. Tôi sẽ kiểm tra cỡ của bạn.")],
    listenTask: "Nghe lý do đổi trả và giải pháp khách hàng chọn.", speakTask: "Giải thích một vấn đề với món đồ và yêu cầu giải pháp."
  },
  {
    id: "pre-intermediate-healthy-routine", en: "A Better Evening Routine", vi: "Thói quen buổi tối tốt hơn", baseTopic: "Sức khỏe hằng ngày", level: "A2", stageId: "pre-intermediate", variant: "Nói về thói quen",
    lines: [line("female", "You look tired today.", "Hôm nay bạn trông mệt."), line("male", "I stayed up late watching videos again.", "Mình lại thức khuya xem video."), line("female", "Maybe you could turn off your phone at ten.", "Có lẽ bạn có thể tắt điện thoại lúc 10 giờ."), line("male", "That might help, but I use it as an alarm.", "Có thể hữu ích, nhưng mình dùng điện thoại làm báo thức."), line("female", "Put it across the room, so you won’t keep checking it.", "Hãy đặt nó ở phía bên kia phòng để bạn không xem liên tục."), line("male", "I’ll try that tonight.", "Tối nay mình sẽ thử.")],
    listenTask: "Nghe nguyên nhân gây mệt và giải pháp được đề xuất.", speakTask: "Mô tả một thói quen muốn thay đổi và đưa ra gợi ý."
  },
  {
    id: "pre-intermediate-museum", en: "Choosing a Museum Tour", vi: "Chọn chuyến tham quan bảo tàng", baseTopic: "Du lịch", level: "A2", stageId: "pre-intermediate", variant: "So sánh lịch trình",
    lines: [line("female", "There are two museum tours this afternoon.", "Chiều nay có hai chuyến tham quan bảo tàng."), line("male", "What time do they start?", "Chúng bắt đầu lúc mấy giờ?"), line("female", "One starts at two, and the other starts at four.", "Một chuyến bắt đầu lúc 2 giờ, chuyến kia lúc 4 giờ."), line("male", "Let’s take the early tour. We have dinner at five.", "Hãy chọn chuyến sớm. Chúng ta ăn tối lúc 5 giờ."), line("female", "Agreed. Then we won’t need to rush.", "Đồng ý. Như vậy chúng ta sẽ không phải vội."), line("male", "I’ll book two tickets now.", "Mình sẽ đặt hai vé ngay.")],
    listenTask: "Nghe hai giờ khởi hành và lý do chọn chuyến sớm.", speakTask: "So sánh hai lịch trình và thống nhất một lựa chọn."
  },

  {
    id: "intermediate-lost-wallet", en: "The Missing Wallet", vi: "Chiếc ví bị thất lạc", baseTopic: "Xử lý sự cố", level: "B1", stageId: "intermediate", variant: "Kể lại trải nghiệm",
    lines: [line("female", "You look worried. What happened?", "Bạn trông lo lắng. Có chuyện gì vậy?"), line("male", "I can’t find my wallet. I last used it at the café.", "Mình không tìm thấy ví. Lần cuối mình dùng nó là ở quán cà phê."), line("female", "Did you check your bag carefully?", "Bạn đã kiểm tra kỹ túi chưa?"), line("male", "Yes. I also called the café, but they haven’t found it.", "Rồi. Mình cũng gọi quán, nhưng họ chưa tìm thấy."), line("female", "Cancel your bank card first. Then we can retrace your route.", "Trước tiên hãy khóa thẻ ngân hàng. Sau đó chúng ta có thể đi lại lộ trình."), line("male", "You’re right. That will protect my money while I keep looking.", "Bạn nói đúng. Như vậy tiền của mình sẽ an toàn trong lúc tìm tiếp."), line("female", "I’ll come with you. Two pairs of eyes are better than one.", "Mình sẽ đi cùng. Hai người tìm vẫn tốt hơn một.")],
    listenTask: "Sắp xếp các hành động xử lý chiếc ví bị mất.", speakTask: "Kể một sự cố nhỏ: chuyện gì xảy ra, bạn làm gì và kết quả ra sao."
  },
  {
    id: "intermediate-group-project", en: "A Fairer Group Project", vi: "Dự án nhóm công bằng hơn", baseTopic: "Làm việc nhóm", level: "B1", stageId: "intermediate", variant: "Giải quyết vấn đề",
    lines: [line("female", "We’re falling behind on the history project.", "Chúng ta đang chậm tiến độ dự án lịch sử."), line("male", "I think the jobs aren’t divided clearly.", "Mình nghĩ các phần việc chưa được chia rõ."), line("female", "That’s true. I’ve been researching and making all the slides.", "Đúng vậy. Mình vừa nghiên cứu vừa làm toàn bộ slide."), line("male", "I’m sorry. I didn’t realise you had both tasks.", "Mình xin lỗi. Mình không nhận ra bạn làm cả hai việc."), line("female", "Could you make the slides while I finish the research?", "Bạn có thể làm slide trong lúc mình hoàn thành nghiên cứu không?"), line("male", "Yes, and I’ll ask Sam to check our sources.", "Được, và mình sẽ nhờ Sam kiểm tra nguồn."), line("female", "Great. Let’s share an update tomorrow afternoon.", "Tuyệt. Chiều mai chúng ta cùng cập nhật tiến độ nhé.")],
    listenTask: "Nghe nguyên nhân chậm tiến độ và cách chia lại ba phần việc.", speakTask: "Nêu vấn đề nhóm, đề nghị phân công rõ và chốt thời hạn."
  },
  {
    id: "intermediate-travel-delay", en: "A Delayed Train", vi: "Chuyến tàu bị hoãn", baseTopic: "Du lịch", level: "B1", stageId: "intermediate", variant: "Thay đổi kế hoạch",
    lines: [line("female", "The board says our train is delayed by ninety minutes.", "Bảng báo chuyến tàu của chúng ta bị hoãn 90 phút."), line("male", "Then we’ll miss the last bus to the hotel.", "Vậy chúng ta sẽ lỡ chuyến xe buýt cuối đến khách sạn."), line("female", "We could take a taxi, but it might be expensive.", "Chúng ta có thể đi taxi, nhưng có thể sẽ đắt."), line("male", "Let me call the hotel. They may have a shuttle.", "Để mình gọi khách sạn. Có thể họ có xe đưa đón."), line("female", "Good idea. I’ll also check whether our tickets can be changed.", "Ý hay. Mình cũng sẽ kiểm tra xem có thể đổi vé không."), line("male", "The hotel can collect us at ten. We just need to confirm.", "Khách sạn có thể đón chúng ta lúc 10 giờ. Chúng ta chỉ cần xác nhận."), line("female", "Perfect. The delay is annoying, but the problem is solved.", "Tuyệt. Việc hoãn tàu thật phiền, nhưng vấn đề đã được giải quyết.")],
    listenTask: "Nghe vấn đề, hai phương án và giải pháp cuối cùng.", speakTask: "Ứng biến khi kế hoạch đi lại thay đổi và giải thích lựa chọn."
  },
  {
    id: "intermediate-neighbour-noise", en: "A Quiet Conversation", vi: "Một cuộc trao đổi nhẹ nhàng", baseTopic: "Hàng xóm", level: "B1", stageId: "intermediate", variant: "Phàn nàn lịch sự",
    lines: [line("female", "Hi, Daniel. Could I talk to you about the music last night?", "Chào Daniel. Mình có thể nói về tiếng nhạc tối qua không?"), line("male", "Of course. Was it too loud?", "Được chứ. Nó to quá phải không?"), line("female", "A little. I had an early meeting and couldn’t sleep.", "Hơi to. Mình có cuộc họp sớm nên không ngủ được."), line("male", "I’m sorry. Some friends stayed later than expected.", "Mình xin lỗi. Mấy người bạn ở lại muộn hơn dự kiến."), line("female", "I understand. Could you lower it after ten next time?", "Mình hiểu. Lần sau bạn có thể giảm âm lượng sau 10 giờ không?"), line("male", "Absolutely. Please text me if it happens again.", "Chắc chắn rồi. Nếu lại xảy ra, bạn cứ nhắn cho mình."), line("female", "Thanks. I appreciate that.", "Cảm ơn. Mình rất trân trọng điều đó.")],
    listenTask: "Nhận biết lời phàn nàn, lời giải thích và thỏa thuận.", speakTask: "Nêu một vấn đề tế nhị bằng giọng bình tĩnh và đề nghị cụ thể."
  },
  {
    id: "intermediate-volunteering", en: "The Community Garden", vi: "Vườn cộng đồng", baseTopic: "Tình nguyện", level: "B1", stageId: "intermediate", variant: "Tổ chức hoạt động",
    lines: [line("female", "The community garden needs volunteers this Sunday.", "Vườn cộng đồng cần tình nguyện viên vào Chủ nhật này."), line("male", "What kind of help do they need?", "Họ cần giúp những việc gì?"), line("female", "Planting vegetables, painting signs, and clearing rubbish.", "Trồng rau, sơn biển báo và dọn rác."), line("male", "I’m not good at gardening, but I can paint.", "Mình không giỏi làm vườn, nhưng có thể sơn."), line("female", "That’s useful. I’ll bring gloves and work on the plants.", "Như vậy rất hữu ích. Mình sẽ mang găng tay và chăm cây."), line("male", "Shall we invite two more people?", "Chúng ta mời thêm hai người nhé?"), line("female", "Yes. With a small team, we can finish before lunch.", "Được. Với một nhóm nhỏ, chúng ta có thể xong trước bữa trưa.")],
    listenTask: "Nghe các nhiệm vụ và việc mỗi người chọn.", speakTask: "Tổ chức một hoạt động cộng đồng, chia vai và nêu mục tiêu."
  },

  {
    id: "upper-intermediate-remote-work", en: "Working from Home or the Office", vi: "Làm ở nhà hay tại văn phòng", baseTopic: "Công việc", level: "B2", stageId: "upper-intermediate", variant: "So sánh lựa chọn",
    lines: [line("female", "Our team can choose two remote days each week. Which days would work best?", "Nhóm có thể chọn hai ngày làm từ xa mỗi tuần. Ngày nào phù hợp nhất?"), line("male", "I’d choose Monday and Friday because they involve fewer meetings.", "Tôi chọn thứ Hai và thứ Sáu vì ít cuộc họp hơn."), line("female", "Friday makes sense, but Monday is when we set priorities together.", "Thứ Sáu hợp lý, nhưng thứ Hai là lúc chúng ta cùng xác định ưu tiên."), line("male", "Fair point. What about Tuesday instead?", "Ý hợp lý. Vậy thứ Ba thì sao?"), line("female", "That would preserve team planning and still give us focused time.", "Như vậy vừa giữ được việc lập kế hoạch nhóm vừa có thời gian tập trung."), line("male", "Let’s try Tuesday and Friday for a month, then review the results.", "Hãy thử thứ Ba và thứ Sáu trong một tháng rồi đánh giá kết quả."), line("female", "Agreed. A trial will give us evidence rather than assumptions.", "Đồng ý. Thử nghiệm sẽ cho chúng ta bằng chứng thay vì phỏng đoán.")],
    listenTask: "Theo dõi lập luận ủng hộ và phản đối từng ngày làm từ xa.", speakTask: "So sánh hai phương án, nhượng bộ một điểm và đề xuất thử nghiệm."
  },
  {
    id: "upper-intermediate-friend-advice", en: "A Difficult Career Choice", vi: "Một lựa chọn nghề nghiệp khó", baseTopic: "Lời khuyên", level: "B2", stageId: "upper-intermediate", variant: "Đưa lời khuyên cân bằng",
    lines: [line("female", "I’ve been offered a better-paid job, but it’s in another city.", "Mình được mời một công việc lương cao hơn, nhưng ở thành phố khác."), line("male", "What matters most to you at this stage?", "Ở giai đoạn này, điều gì quan trọng nhất với bạn?"), line("female", "I want to grow professionally, yet I don’t want to lose my support network.", "Mình muốn phát triển nghề nghiệp nhưng không muốn mất mạng lưới hỗ trợ."), line("male", "Before deciding, find out whether the company offers remote weeks or relocation support.", "Trước khi quyết định, hãy tìm hiểu xem công ty có tuần làm từ xa hay hỗ trợ chuyển chỗ ở không."), line("female", "That could reduce the risk. I’ve only considered accepting or refusing.", "Điều đó có thể giảm rủi ro. Mình mới chỉ nghĩ đến nhận hoặc từ chối."), line("male", "You might also visit the city and estimate the real cost of living.", "Bạn cũng có thể đến thăm thành phố và ước tính chi phí sinh hoạt thực tế."), line("female", "Good advice. I need more information, not a rushed answer.", "Lời khuyên hay. Mình cần thêm thông tin chứ không phải câu trả lời vội vàng."), line("male", "Exactly. A good opportunity should still fit the life you want.", "Chính xác. Một cơ hội tốt vẫn phải phù hợp với cuộc sống bạn mong muốn.")],
    listenTask: "Nghe các giá trị, rủi ro và thông tin cần thu thập trước khi quyết định.", speakTask: "Đưa lời khuyên có điều kiện, cân nhắc cả lợi ích lẫn rủi ro."
  },
  {
    id: "upper-intermediate-school-phones", en: "Phones in the Classroom", vi: "Điện thoại trong lớp học", baseTopic: "Giáo dục", level: "B2", stageId: "upper-intermediate", variant: "Bảo vệ quan điểm",
    lines: [line("female", "I think phones should be completely banned during lessons.", "Tôi nghĩ điện thoại nên bị cấm hoàn toàn trong giờ học."), line("male", "They can be distracting, but a total ban may remove useful learning tools.", "Chúng có thể gây xao nhãng, nhưng cấm hoàn toàn có thể loại bỏ công cụ học hữu ích."), line("female", "Students often say they’re researching when they’re actually messaging friends.", "Học sinh thường nói đang nghiên cứu trong khi thực ra nhắn tin cho bạn."), line("male", "Then the rule could focus on permission: phones away unless the teacher asks for them.", "Vậy quy tắc có thể tập trung vào sự cho phép: cất điện thoại trừ khi giáo viên yêu cầu."), line("female", "That’s more practical, although it depends on consistent enforcement.", "Cách đó thực tế hơn, dù phụ thuộc vào việc thực thi nhất quán."), line("male", "True. Teachers would need one clear policy across the school.", "Đúng. Giáo viên cần một chính sách rõ ràng chung toàn trường."), line("female", "I can support controlled use if consequences are also clear.", "Tôi có thể ủng hộ việc sử dụng có kiểm soát nếu hậu quả vi phạm cũng rõ ràng."), line("male", "Then we agree on limits, even if we started from different positions.", "Vậy chúng ta thống nhất về giới hạn, dù ban đầu có quan điểm khác nhau.")],
    listenTask: "Xác định quan điểm ban đầu, phản biện và điểm đồng thuận cuối cùng.", speakTask: "Bảo vệ một quan điểm, thừa nhận ý hợp lý của phía khác và tìm điểm chung."
  },
  {
    id: "upper-intermediate-sustainable-trip", en: "A Greener Holiday", vi: "Kỳ nghỉ xanh hơn", baseTopic: "Môi trường", level: "B2", stageId: "upper-intermediate", variant: "Cân nhắc đánh đổi",
    lines: [line("female", "Flying is much faster, but the train would produce fewer emissions.", "Đi máy bay nhanh hơn nhiều, nhưng tàu hỏa tạo ra ít khí thải hơn."), line("male", "The train also takes nearly a full day and costs more.", "Tàu hỏa cũng mất gần cả ngày và tốn hơn."), line("female", "We could take an overnight train and save one night at a hotel.", "Chúng ta có thể đi tàu đêm và tiết kiệm một đêm khách sạn."), line("male", "That improves the cost, though we might arrive tired.", "Như vậy chi phí hợp lý hơn, dù chúng ta có thể đến nơi trong trạng thái mệt."), line("female", "I’m willing to accept that if we book a comfortable cabin.", "Mình sẵn sàng chấp nhận nếu đặt khoang thoải mái."), line("male", "All right. Let’s compare the total price, not just the ticket.", "Được. Hãy so sánh tổng chi phí chứ không chỉ giá vé."), line("female", "Exactly. A greener choice should also be realistic.", "Chính xác. Một lựa chọn xanh hơn cũng cần thực tế."), line("male", "If the difference is reasonable, we’ll take the train.", "Nếu chênh lệch hợp lý, chúng ta sẽ đi tàu.")],
    listenTask: "Ghi lại các đánh đổi về thời gian, chi phí, sự thoải mái và môi trường.", speakTask: "So sánh lựa chọn dựa trên ít nhất ba tiêu chí và đưa quyết định có điều kiện."
  },
  {
    id: "upper-intermediate-feedback", en: "Feedback on a Presentation", vi: "Góp ý cho bài thuyết trình", baseTopic: "Giao tiếp chuyên nghiệp", level: "B2", stageId: "upper-intermediate", variant: "Góp ý xây dựng",
    lines: [line("female", "Could you give me honest feedback on my presentation?", "Bạn có thể góp ý thật lòng về bài thuyết trình của mình không?"), line("male", "Your examples were strong, and the opening caught everyone’s attention.", "Các ví dụ rất tốt và phần mở đầu thu hút mọi người."), line("female", "Thanks. What should I improve?", "Cảm ơn. Mình nên cải thiện điều gì?"), line("male", "The middle section had too much detail, so your main message became less clear.", "Phần giữa có quá nhiều chi tiết nên thông điệp chính kém rõ."), line("female", "Would cutting two slides solve that?", "Cắt bớt hai slide có giải quyết được không?"), line("male", "It would help. You could also state the key point before showing the data.", "Sẽ hữu ích. Bạn cũng có thể nêu ý chính trước khi trình bày dữ liệu."), line("female", "That’s specific enough for me to act on. Thank you.", "Góp ý đủ cụ thể để mình chỉnh sửa. Cảm ơn bạn."), line("male", "You’re welcome. The content is good; it just needs a clearer path.", "Không có gì. Nội dung tốt; chỉ cần mạch trình bày rõ hơn.")],
    listenTask: "Phân biệt lời khen, điểm cần cải thiện và hai hành động cụ thể.", speakTask: "Đưa phản hồi theo cấu trúc điểm mạnh–vấn đề–đề xuất."
  },

  {
    id: "advanced-ai-work", en: "Using AI Without Losing Judgment", vi: "Dùng AI mà không đánh mất khả năng phán đoán", baseTopic: "Công nghệ", level: "C1", stageId: "advanced", variant: "Thảo luận sâu",
    lines: [line("female", "AI has made routine research faster, but I worry that we’re outsourcing too much judgment.", "AI giúp nghiên cứu thường ngày nhanh hơn, nhưng tôi lo chúng ta đang giao phó quá nhiều khả năng phán đoán."), line("male", "The risk is real, although rejecting the tools would waste their potential.", "Rủi ro là có thật, dù từ chối công cụ sẽ lãng phí tiềm năng."), line("female", "I’m not suggesting rejection. I’m arguing for a visible review process.", "Tôi không đề nghị từ chối. Tôi cho rằng cần quy trình kiểm tra minh bạch."), line("male", "What would that look like in practice?", "Trong thực tế quy trình đó sẽ như thế nào?"), line("female", "We would record which claims came from the system, verify important ones, and assign a person to own the final decision.", "Chúng ta ghi lại tuyên bố nào đến từ hệ thống, kiểm chứng các điểm quan trọng và giao một người chịu trách nhiệm quyết định cuối."), line("male", "That preserves accountability, but it could slow down low-risk tasks.", "Cách đó giữ được trách nhiệm giải trình, nhưng có thể làm chậm các việc ít rủi ro."), line("female", "Then the level of review should match the possible harm, rather than being identical for every task.", "Vậy mức độ kiểm tra nên tương xứng với hậu quả có thể xảy ra thay vì giống nhau cho mọi việc."), line("male", "That’s a sensible distinction: automate freely where errors are reversible, and scrutinise decisions where they aren’t.", "Đó là phân biệt hợp lý: tự động hóa thoải mái khi lỗi có thể khắc phục, và xem xét kỹ khi không thể."), line("female", "Exactly. The goal is not less technology, but better human responsibility around it.", "Chính xác. Mục tiêu không phải ít công nghệ hơn mà là trách nhiệm con người tốt hơn quanh công nghệ.")],
    listenTask: "Tóm tắt rủi ro, đề xuất, phản biện và nguyên tắc cuối cùng.", speakTask: "Trình bày quan điểm có giới hạn, trả lời phản biện và kết luận bằng một nguyên tắc."
  },
  {
    id: "advanced-public-space", en: "Redesigning the Town Square", vi: "Thiết kế lại quảng trường", baseTopic: "Cộng đồng", level: "C1", stageId: "advanced", variant: "Đàm phán ưu tiên",
    lines: [line("female", "The current plan gives most of the square to events, leaving little quiet space for everyday use.", "Kế hoạch hiện tại dành phần lớn quảng trường cho sự kiện, để lại ít không gian yên tĩnh dùng hằng ngày."), line("male", "Large events bring income to local businesses, so we shouldn’t underestimate their value.", "Sự kiện lớn mang doanh thu cho doanh nghiệp địa phương nên không thể xem nhẹ giá trị đó."), line("female", "Agreed, but the square serves residents all year, not only during festivals.", "Đồng ý, nhưng quảng trường phục vụ cư dân quanh năm chứ không chỉ lúc lễ hội."), line("male", "Could movable seating allow the space to change according to need?", "Ghế di động có thể giúp không gian thay đổi theo nhu cầu không?"), line("female", "Yes, provided we also keep shade trees and a safe route through the centre.", "Có, miễn là vẫn giữ cây tạo bóng mát và lối đi an toàn qua trung tâm."), line("male", "Event organisers may object to permanent trees blocking sight lines.", "Nhà tổ chức có thể phản đối cây cố định che tầm nhìn."), line("female", "We could group the trees around the edges and use temporary shade in the central area.", "Ta có thể nhóm cây quanh rìa và dùng mái che tạm ở khu trung tâm."), line("male", "That balances commercial events, daily comfort, and accessibility.", "Cách đó cân bằng sự kiện thương mại, tiện nghi hằng ngày và khả năng tiếp cận."), line("female", "Let’s revise the plan around those three tests and invite public feedback.", "Hãy sửa kế hoạch theo ba tiêu chí đó và mời cộng đồng góp ý.")],
    listenTask: "Theo dõi các nhóm lợi ích, mâu thuẫn và phương án thỏa hiệp.", speakTask: "Đàm phán giữa các ưu tiên cạnh tranh và đề xuất giải pháp dung hòa."
  },
  {
    id: "advanced-failure", en: "When a Good Project Fails", vi: "Khi một dự án tốt thất bại", baseTopic: "Lãnh đạo", level: "C1", stageId: "advanced", variant: "Phân tích nguyên nhân",
    lines: [line("female", "The mentoring programme had strong funding and enthusiastic volunteers, yet participation collapsed after two months.", "Chương trình cố vấn có kinh phí tốt và tình nguyện viên nhiệt tình, nhưng lượng tham gia giảm mạnh sau hai tháng."), line("male", "Perhaps the organisers confused initial interest with long-term commitment.", "Có lẽ ban tổ chức nhầm lẫn sự quan tâm ban đầu với cam kết lâu dài."), line("female", "That contributed, but interviews showed a more practical problem: meeting times changed every week.", "Điều đó có phần đúng, nhưng phỏng vấn cho thấy vấn đề thực tế hơn: giờ gặp thay đổi hằng tuần."), line("male", "So the design demanded flexibility from people who had joined because they needed structure.", "Vậy thiết kế đòi hỏi sự linh hoạt từ những người tham gia vì họ cần khuôn khổ ổn định."), line("female", "Exactly. The programme was valuable in principle but unreliable in experience.", "Chính xác. Về nguyên tắc chương trình có giá trị nhưng trải nghiệm lại thiếu ổn định."), line("male", "Would a fixed monthly schedule be enough to restart it?", "Lịch cố định theo tháng có đủ để khởi động lại không?"), line("female", "It’s necessary but not sufficient. We should also ask participants to choose times before recruiting mentors.", "Đó là điều cần nhưng chưa đủ. Ta cũng nên để người tham gia chọn giờ trước khi tuyển cố vấn."), line("male", "Then the broader lesson is to test the delivery model, not merely the appeal of the idea.", "Vậy bài học rộng hơn là phải kiểm tra mô hình triển khai chứ không chỉ sức hấp dẫn của ý tưởng."), line("female", "Precisely. Good intentions cannot compensate for a system people cannot depend on.", "Đúng vậy. Ý định tốt không thể bù cho một hệ thống mà mọi người không thể tin cậy.")],
    listenTask: "Phân biệt nguyên nhân bề mặt, nguyên nhân gốc và bài học tổng quát.", speakTask: "Phân tích một thất bại, dùng bằng chứng để sửa giả thuyết và rút ra bài học."
  },
  {
    id: "advanced-cultural-tradition", en: "Keeping a Tradition Alive", vi: "Giữ gìn một truyền thống", baseTopic: "Văn hóa", level: "C1", stageId: "advanced", variant: "Đánh giá thay đổi",
    lines: [line("female", "The festival committee wants to modernise the programme to attract younger residents.", "Ban lễ hội muốn hiện đại hóa chương trình để thu hút cư dân trẻ."), line("male", "Modernisation may help, but if the event loses its history, it becomes interchangeable with any street fair.", "Hiện đại hóa có thể hữu ích, nhưng nếu mất lịch sử, sự kiện sẽ chẳng khác hội chợ đường phố nào."), line("female", "True. Still, preserving every detail unchanged can turn tradition into a museum piece.", "Đúng. Tuy nhiên giữ nguyên mọi chi tiết có thể biến truyền thống thành hiện vật bảo tàng."), line("male", "Then we need to identify what carries the meaning and what is merely habit.", "Vậy ta cần xác định điều gì mang ý nghĩa và điều gì chỉ là thói quen."), line("female", "The community procession and shared meal express belonging; the printed schedule does not.", "Đoàn rước cộng đồng và bữa ăn chung thể hiện sự gắn kết; lịch in giấy thì không."), line("male", "So we could keep the central rituals while changing the music, communication, and timing.", "Ta có thể giữ nghi lễ cốt lõi nhưng thay đổi âm nhạc, cách truyền thông và thời gian."), line("female", "And younger residents should help design those changes rather than simply being marketed to.", "Và cư dân trẻ nên tham gia thiết kế thay đổi thay vì chỉ là đối tượng được quảng bá."), line("male", "That would make renewal part of the tradition’s continuity, not a threat to it.", "Như vậy đổi mới trở thành một phần của sự tiếp nối truyền thống chứ không phải mối đe dọa."), line("female", "Exactly. A living tradition survives by carrying its meaning into new forms.", "Chính xác. Một truyền thống sống còn bằng cách đưa ý nghĩa của nó vào những hình thức mới.")],
    listenTask: "Xác định sự khác biệt giữa giá trị cốt lõi và hình thức có thể thay đổi.", speakTask: "Đánh giá một thay đổi văn hóa bằng cách cân bằng tính liên tục và đổi mới."
  },
  {
    id: "advanced-data-story", en: "What the Numbers Do Not Say", vi: "Điều những con số không nói", baseTopic: "Dữ liệu", level: "C1", stageId: "advanced", variant: "Diễn giải thận trọng",
    lines: [line("female", "Customer satisfaction rose by twelve per cent after the redesign, which looks like a clear success.", "Mức hài lòng của khách hàng tăng 12% sau thiết kế mới, có vẻ là thành công rõ ràng."), line("male", "It’s encouraging, but do we know who responded to the survey?", "Đáng khích lệ, nhưng ta có biết ai trả lời khảo sát không?"), line("female", "Mostly regular customers. New users were underrepresented.", "Chủ yếu là khách quen. Người dùng mới được đại diện ít."), line("male", "Then the result may tell us that loyal users adapted well, not that the design works for everyone.", "Vậy kết quả có thể cho thấy người dùng trung thành thích nghi tốt chứ không phải thiết kế phù hợp với mọi người."), line("female", "That’s a fair limitation. However, support requests also fell significantly.", "Đó là giới hạn hợp lý. Tuy nhiên, yêu cầu hỗ trợ cũng giảm đáng kể."), line("male", "That strengthens the case, although fewer requests could also mean people gave up.", "Điều đó củng cố lập luận, dù ít yêu cầu hơn cũng có thể do người dùng bỏ cuộc."), line("female", "We should compare completion rates and interview those who left early.", "Ta nên so sánh tỷ lệ hoàn thành và phỏng vấn người rời đi sớm."), line("male", "Agreed. The evidence supports cautious optimism, not a final verdict.", "Đồng ý. Bằng chứng ủng hộ sự lạc quan thận trọng chứ chưa phải kết luận cuối."), line("female", "I’ll present it that way and specify what we still need to learn.", "Tôi sẽ trình bày như vậy và nêu rõ những gì vẫn cần tìm hiểu.")],
    listenTask: "Nhận biết tuyên bố, giới hạn dữ liệu, cách giải thích khác và kết luận thận trọng.", speakTask: "Diễn giải số liệu mà không phóng đại, nêu giới hạn và bước kiểm chứng tiếp theo."
  },

  {
    id: "proficient-apology", en: "An Apology That Repairs Trust", vi: "Lời xin lỗi hàn gắn niềm tin", baseTopic: "Quan hệ", level: "C2", stageId: "proficient", variant: "Điều chỉnh sắc thái",
    lines: [line("female", "I owe you a proper apology. I dismissed your concern in the meeting, and doing so in front of the team made it worse.", "Tôi nợ bạn một lời xin lỗi đúng nghĩa. Tôi đã gạt đi lo ngại của bạn trong cuộc họp, và làm vậy trước cả nhóm khiến mọi chuyện tệ hơn."), line("male", "I appreciate you saying that. What bothered me most was not the disagreement, but the implication that I hadn’t thought it through.", "Tôi trân trọng lời đó. Điều làm tôi khó chịu nhất không phải bất đồng mà là hàm ý rằng tôi chưa suy nghĩ kỹ."), line("female", "You’re right. I attacked the quality of your judgment instead of examining the argument, and that was unfair.", "Bạn nói đúng. Tôi công kích chất lượng phán đoán của bạn thay vì xem xét lập luận, và như vậy không công bằng."), line("male", "We were both under pressure, but I need to know it won’t become our normal way of working.", "Cả hai đều chịu áp lực, nhưng tôi cần biết đó sẽ không trở thành cách làm việc bình thường."), line("female", "It won’t. At tomorrow’s meeting, I’ll correct the impression I created and credit the risk you identified.", "Sẽ không. Trong cuộc họp ngày mai, tôi sẽ sửa lại ấn tượng mình gây ra và ghi nhận rủi ro bạn đã chỉ ra."), line("male", "That would help. I don’t need you to agree with me; I need disagreement to remain respectful.", "Điều đó sẽ hữu ích. Tôi không cần bạn đồng ý; tôi cần bất đồng vẫn giữ sự tôn trọng."), line("female", "Understood. If I slip into that tone again, please flag it immediately rather than letting it build.", "Tôi hiểu. Nếu tôi lại dùng giọng đó, hãy chỉ ra ngay thay vì để tích tụ."), line("male", "I can do that. And I’ll try not to read every abrupt response as personal criticism.", "Tôi có thể làm vậy. Và tôi sẽ cố không xem mọi phản hồi đột ngột là chỉ trích cá nhân."), line("female", "Thank you. I’d like us to come out of this with a stronger working agreement, not merely a closed incident.", "Cảm ơn. Tôi muốn chúng ta bước ra khỏi chuyện này với thỏa thuận làm việc tốt hơn, chứ không chỉ khép lại một sự cố."), line("male", "So would I. Let’s treat tomorrow as the first test of that agreement.", "Tôi cũng vậy. Hãy xem ngày mai là phép thử đầu tiên cho thỏa thuận đó.")],
    listenTask: "Phân tích cách lời xin lỗi nhận trách nhiệm, gọi đúng tổn hại và đề xuất sửa chữa.", speakTask: "Xin lỗi chân thành, tránh biện minh và cùng xây dựng nguyên tắc cho tương lai."
  },
  {
    id: "proficient-policy", en: "A Policy That Sounds Fair", vi: "Một chính sách nghe có vẻ công bằng", baseTopic: "Chính sách", level: "C2", stageId: "proficient", variant: "Phân tích sắc thái",
    lines: [line("female", "A uniform deadline sounds fair because everyone receives the same amount of time.", "Một hạn chót chung nghe có vẻ công bằng vì mọi người có cùng lượng thời gian."), line("male", "It ensures equality of treatment, but not necessarily equality of opportunity.", "Nó bảo đảm đối xử như nhau, nhưng chưa chắc bảo đảm cơ hội như nhau."), line("female", "I take the distinction, yet flexible deadlines can create uncertainty and perceptions of favouritism.", "Tôi hiểu sự phân biệt đó, nhưng hạn linh hoạt có thể tạo bất định và cảm giác thiên vị."), line("male", "Only if the criteria are vague. We could define limited grounds for adjustment and publish them in advance.", "Chỉ khi tiêu chí mơ hồ. Ta có thể xác định các lý do điều chỉnh có giới hạn và công bố trước."), line("female", "That would improve transparency, though administrators would still exercise judgment at the margins.", "Như vậy minh bạch hơn, dù người quản lý vẫn phải phán đoán ở các trường hợp ranh giới."), line("male", "No policy eliminates judgment; some simply conceal where it occurs.", "Không chính sách nào loại bỏ phán đoán; một số chỉ che giấu nơi nó diễn ra."), line("female", "Fair enough. My concern is that discretion tends to benefit people who know how to ask.", "Hợp lý. Điều tôi lo là quyền linh hoạt thường có lợi cho người biết cách yêu cầu."), line("male", "Then adjustments should be proactively explained, not granted only to the most confident applicants.", "Vậy điều chỉnh nên được chủ động giải thích, không chỉ trao cho người nộp đơn tự tin nhất."), line("female", "In that case, a structured exception process may be fairer than a rigid rule masquerading as neutrality.", "Trong trường hợp đó, quy trình ngoại lệ có cấu trúc có thể công bằng hơn quy tắc cứng nhắc khoác áo trung lập."), line("male", "Exactly. Consistency matters, but consistency should serve fairness rather than substitute for it.", "Chính xác. Tính nhất quán quan trọng, nhưng nên phục vụ công bằng chứ không thay thế nó.")],
    listenTask: "Theo dõi sự khác biệt giữa bình đẳng, công bằng, nhất quán và quyền linh hoạt.", speakTask: "Thảo luận một chính sách bằng cách làm rõ khái niệm và hệ quả ngoài dự kiến."
  },
  {
    id: "proficient-medical-uncertainty", en: "Communicating Uncertainty", vi: "Truyền đạt sự không chắc chắn", baseTopic: "Giao tiếp chuyên môn", level: "C2", stageId: "proficient", variant: "Cân bằng độ chính xác và sự rõ ràng",
    lines: [line("female", "The early results are promising, but the sample is too small for us to speak with confidence.", "Kết quả ban đầu đầy hứa hẹn, nhưng mẫu quá nhỏ để chúng ta có thể nói với sự chắc chắn."), line("male", "If we emphasise uncertainty too heavily, people may assume the treatment has no value at all.", "Nếu nhấn mạnh sự không chắc chắn quá mức, mọi người có thể cho rằng phương pháp không có giá trị."), line("female", "True, but optimism without proportion could be mistaken for a recommendation.", "Đúng, nhưng lạc quan không đúng mức có thể bị hiểu nhầm thành khuyến nghị."), line("male", "Perhaps we should separate what we observed from what we infer.", "Có lẽ ta nên tách điều quan sát được khỏi điều suy luận."), line("female", "Yes: symptoms improved in this group; we do not yet know whether the treatment caused the improvement or whether it will generalise.", "Đúng: triệu chứng cải thiện trong nhóm này; ta chưa biết phương pháp có gây ra cải thiện hay có áp dụng rộng được không."), line("male", "That is accurate, though it may still sound abstract to a non-specialist audience.", "Cách đó chính xác, dù vẫn có thể trừu tượng với người không chuyên."), line("female", "Then we can add an analogy: this is a signal worth investigating, not proof on which to base a decision.", "Ta có thể thêm phép so sánh: đây là tín hiệu đáng nghiên cứu, không phải bằng chứng để dựa vào ra quyết định."), line("male", "Good. We should also say what evidence would change our level of confidence.", "Tốt. Ta cũng nên nói bằng chứng nào sẽ thay đổi mức độ tin cậy."), line("female", "A larger controlled study with longer follow-up would do that.", "Một nghiên cứu đối chứng lớn hơn với thời gian theo dõi dài hơn sẽ làm được điều đó."), line("male", "Then the message is neither reassuring nor alarming; it is useful because it shows what is known and what remains open.", "Vậy thông điệp không nhằm trấn an hay báo động; nó hữu ích vì cho thấy điều đã biết và điều còn bỏ ngỏ.")],
    listenTask: "Phân biệt quan sát, suy luận, mức độ chắc chắn và bằng chứng cần bổ sung.", speakTask: "Giải thích sự không chắc chắn chính xác nhưng dễ hiểu cho người không chuyên."
  },
  {
    id: "proficient-leadership", en: "Authority Without Certainty", vi: "Lãnh đạo khi chưa chắc chắn", baseTopic: "Lãnh đạo", level: "C2", stageId: "proficient", variant: "Giữ giọng điệu phù hợp",
    lines: [line("female", "The team expects a decisive answer, but the evidence genuinely supports more than one course of action.", "Nhóm mong đợi câu trả lời dứt khoát, nhưng bằng chứng thực sự ủng hộ nhiều hướng hành động."), line("male", "Indecision will unsettle them more than an imperfect choice.", "Do dự sẽ khiến họ bất an hơn một lựa chọn chưa hoàn hảo."), line("female", "Agreed, though manufactured certainty may buy confidence today at the cost of trust tomorrow.", "Đồng ý, nhưng sự chắc chắn giả tạo có thể mua niềm tin hôm nay bằng cái giá là uy tín ngày mai."), line("male", "How do you lead clearly without pretending to know what you don’t?", "Làm sao lãnh đạo rõ ràng mà không giả vờ biết điều mình không biết?"), line("female", "State the decision, the assumptions behind it, and the conditions that would trigger a change.", "Nêu quyết định, các giả định phía sau và điều kiện khiến ta thay đổi."), line("male", "So the firmness lies in the process rather than in claiming the outcome is guaranteed.", "Vậy sự vững vàng nằm ở quy trình chứ không phải khẳng định kết quả được bảo đảm."), line("female", "Exactly. We can commit to a direction while remaining intellectually open to contrary evidence.", "Chính xác. Ta có thể cam kết theo một hướng mà vẫn cởi mở trí tuệ trước bằng chứng trái chiều."), line("male", "Some may hear that openness as weakness.", "Một số người có thể xem sự cởi mở đó là yếu đuối."), line("female", "Then we frame revision as a planned response to learning, not an embarrassed retreat.", "Vậy ta định nghĩa việc điều chỉnh là phản ứng có kế hoạch trước điều học được, không phải rút lui trong xấu hổ."), line("male", "That strikes the right note: direction now, review later, and no false promises in between.", "Cách đó đúng sắc thái: định hướng hiện tại, xem xét sau, và không có lời hứa giả tạo ở giữa.")],
    listenTask: "Nghe cách hai người phân biệt sự dứt khoát với sự chắc chắn giả tạo.", speakTask: "Thông báo quyết định rõ ràng, nêu giả định và điều kiện xem xét lại."
  },
  {
    id: "proficient-art-value", en: "Who Decides What Art Is Worth?", vi: "Ai quyết định giá trị của nghệ thuật?", baseTopic: "Nghệ thuật", level: "C2", stageId: "proficient", variant: "Thảo luận tự nhiên",
    lines: [line("female", "The exhibition is technically impressive, yet I left feeling that it was designed more for photographs than contemplation.", "Triển lãm ấn tượng về kỹ thuật, nhưng tôi ra về với cảm giác nó được thiết kế để chụp ảnh hơn là chiêm nghiệm."), line("male", "Is that necessarily a flaw? Shared images may be how the work participates in contemporary culture.", "Điều đó nhất thiết là khuyết điểm sao? Hình ảnh được chia sẻ có thể là cách tác phẩm tham gia văn hóa đương đại."), line("female", "Not inherently. My concern is that visibility has become a proxy for value.", "Không hẳn. Tôi lo rằng độ hiển thị đã trở thành đại diện cho giá trị."), line("male", "But older institutions used prestige as a proxy, which was hardly more democratic.", "Nhưng các thiết chế cũ dùng uy tín làm đại diện, điều đó đâu dân chủ hơn."), line("female", "That’s a useful correction. Social attention can challenge gatekeepers, even as it creates new pressures.", "Đó là điều chỉnh hữu ích. Sự chú ý xã hội có thể thách thức người gác cổng, dù tạo áp lực mới."), line("male", "And a work can invite a quick image while rewarding a slower encounter; the two aren’t mutually exclusive.", "Một tác phẩm có thể mời gọi bức ảnh nhanh mà vẫn tưởng thưởng sự tiếp xúc chậm; hai điều không loại trừ nhau."), line("female", "Perhaps I’m reacting to the way the exhibition directed every visitor toward the same spectacular moments.", "Có lẽ tôi phản ứng với cách triển lãm hướng mọi khách đến cùng những khoảnh khắc ngoạn mục."), line("male", "So your objection is less about popularity than about choreography that leaves little room for discovery.", "Vậy phản đối của bạn ít liên quan đến sự nổi tiếng mà về cách dàn dựng để lại ít chỗ cho khám phá."), line("female", "Yes, that captures it better. I want an exhibition to shape attention without exhausting interpretation.", "Đúng, cách nói đó chính xác hơn. Tôi muốn triển lãm định hình sự chú ý mà không làm cạn kiệt diễn giải."), line("male", "Then perhaps its value lies partly in this conversation: it gave us something precise to disagree about.", "Vậy có lẽ một phần giá trị của nó nằm trong cuộc trò chuyện này: nó cho ta một điều cụ thể để bất đồng.")],
    listenTask: "Theo dõi cách hai người điều chỉnh và làm chính xác hơn quan điểm của nhau.", speakTask: "Thảo luận tự nhiên, dùng phản biện để tinh chỉnh quan điểm thay vì chỉ thắng tranh luận."
  },
];
